toolboxes/gtplus/workflow/gtPlusISMRMRDReconWorker2DTSPIRIT.h, toolboxes/gtplus/workflow/gtPlusISMRMRDReconWorker3DTSPIRIT.h, toolboxes/registration/optical_flow/cpu/application/hoImageRegContainer2DRegistration.h, toolboxes/registration/optical_flow/cpu/solver/hoImageRegDeformationFieldBidirectionalSolver.h, toolboxes/registration/optical_flow/cpu/solver/hoImageRegDeformationFieldSolver.h, toolboxes/registration/optical_flow/cpu/warper/hoImageRegWarper.h
Optimize the threading for registration progressive mode
a) The nested threading is on for progressive mode
b) for 2D warpping and registration solver, the number of threads is set to be 2, based on experiments on typical perfusion datasets and other cases on integration tests (the gtprep testing time reduced from 6min15s to 5min30s).
=> optimize the threading for registration

gadgets/epi/EPICorrGadget.cpp, gadgets/epi/EPIReconXGadget.cpp, gadgets/gtPlus/GtPlusAccumulatorWorkOrderTriggerGadget.cpp, gadgets/mri_core/MaxwellCorrectionGadget.cpp, gadgets/spiral/SpiralToGenericGadget.cpp, gadgets/spiral/gpuSpiralSensePrepGadget.cpp
The 'strcmp' only caused problem in gpuSpiralSensePrepGadget.cpp file, and my original thought is that it is caused by the different include rules between MSVC and gcc/g++, so I changed a single include file to fix it. But now since we are discussing the std::string comparison, I just changed all unnecessary 'strcmp' to '==', please take a look.
Also may I suggest that an official rules for code format be setup. During my edit, I noticed that both spaces and tabs are used and because the tabs are interpreted differently, it makes the code hard to read. Any rule is better than no rules at all. Linux kernel uses a set of good rules, for example. 
Thanks.
=> Replace strcmp with simple '==' for std::string comparison

gadgets/mri_core/NoiseAdjustGadget.cpp, gadgets/mri_core/NoiseAdjustGadget.h, gadgets/mri_core/default_measurement_dependencies.xml
Add controls in the NoiseAdjust gadget to pass the nonconformant data, such as the body coil surface coil correction data
=> add control in NoiseAdjust to pass nonconformant data

toolboxes/core/NDArray.h, toolboxes/core/cpu/ho2DArray.h, toolboxes/core/cpu/hoNDBoundaryHandler.h, toolboxes/core/cpu/hoNDBoundaryHandler.hxx, toolboxes/core/cpu/hoNDInterpolatorBSpline.hxx, toolboxes/core/cpu/hoNDInterpolatorLinear.hxx, toolboxes/core/cpu/hoNDInterpolatorNearestNeighbor.hxx, toolboxes/core/cpu/image/hoNDImage.h, toolboxes/core/cpu/image/hoNDImage.hxx, toolboxes/core/cpu/math/hoNDImage_util.hxx
Following the discussion, 
a) remove gt_index_type
b) make sure all array access using size_t
c) the boundary condition check and interpolator use long long, since they need to handle negative indices
=> remove gt_index_type

toolboxes/CMakeLists.txt, toolboxes/python_math/CMakeLists.txt, toolboxes/python_math/PythonMath.cpp, toolboxes/python_math/PythonMath.h, toolboxes/python_math/python_math_export.h, toolboxes/python_math/test_python_math.cpp
Could you guys @inati @naegelejd @dchansen take a look at this and see what you think. This is an example of a general Python wrapper class where an explicit function (ismrmrd.grappa.calculate_grappa_unmixing) is exposed from the ismrmrd-python-tools library. It is a fairly complicated function, but I thought it made a good example. 
There are some general functions for getting to and from hoNDArrays and with those, it might actually be possible to do a generic wrapper which could call most python functions, but that could be a next step. 
Let me know what you think.
=> Python math

apps/gadgetron/Gadget.cpp, apps/gadgetron/Gadget.h, apps/gadgetron/gadgetron_info.cpp, gadgets/grappa/GrappaGadget.cpp, gadgets/grappa/GrappaGadget.h, gadgets/mri_core/AcquisitionAccumulateTriggerGadget.cpp, gadgets/mri_core/AcquisitionAccumulateTriggerGadget.h, gadgets/mri_core/CoilReductionGadget.h
This is a first draft for adding a more formal concept of properties to the Gadgets. For illustration purposes, I have converted one gadget (GrappaGadget) to the new system. Please do don't merge just yet. At this point, I would just like some comments. @inati, @dchansen, @naegelejd, @gtdeveloper5  
The way it works at the moment is that on the Gadget (in the header), you can add properties like:
GADGET_PROPERTY(target_coils,int,0);
GADGET_PROPERTY(use_gpu,bool,true);
GADGET_PROPERTY(device_channels,int,0);
GADGET_PROPERTY(uncombined_channels,std::string,"");
GADGET_PROPERTY(uncombined_channels_by_name,std::string,"");
GADGET_PROPERTY(image_series,int,0);
Once you register properties using this macro, it will force the Gadget into a state where properties have to be declared otherwise, an …
=> Gadget properties

gadgets/python/GadgetronPythonMRI.cpp, gadgets/python/PythonGadget.cpp, gadgets/python/PythonGadget.h, gadgets/python/config/python.xml, gadgets/python/config/python_short.xml, gadgets/python/config/python_tpat_snr_scale.xml, gadgets/python/gadgets/accumulate_and_recon.py, gadgets/python/gadgets/rms_coil_combine.py
Create a single PythonGadget type and removed the need for Acquisition and Image Gadgets in Python. The PythonGadget supports all Acquisition and Image types.
Instead of having an ImagePythonGadget (which we would now need multiple versions of to support different data types) and AcquisitionGadget, there is now a single PythonGadget, which supports both all types of ISMRMRD data. 
This is also a precursor for creating a gadgetron_python_to_xml.py script that will take a chain in Python and return it's equivalent xml chain. I ran into difficulties writing that script, since in Python we don't distinguish those types of Gadgets so when converting, it is hard to write the right XML. This PR should make that easy. 
Thoughts? Comments?
=> Create a single PythonGadget

apps/gadgetron/Gadget.cpp, apps/gadgetron/Gadget.h, gadgets/python/PythonGadget.h, gadgets/python/config/python_tpat_snr_scale.xml, gadgets/python/gadgets/gadgetron.py, gadgets/python/gadgets/remove_2x_oversampling.py, gadgets/python/gadgets/tpat_snr_scale.py, gadgets/python/utils/CMakeLists.txt, gadgets/python/utils/gadgetron_python_to_xml.py, gadgets/python/utils/gadgetron_run_python_chain.py, gadgets/python/utils/gadgetron_xml_to_python.py
This PR adds support for properties passed from C++ to Python Gadgets. This is done without violating the requirement that properties usually have to be defined and without using the current exception for Gadgets that don't define properties. It is achieved by overloading the set_parameter function on the PythonGadget and storing the properties that are not defined as such and this list of parameters are then passed on to the Python gadget.  
It also provides a script to convert a Python chain to it's equivalent XML representation. There are some various utilities to support this on the basic Gadget Python class and the GadgetWrapper class. 
It also fixes a bug that caused properties to not be set in the old style map on the gadgets that define properties but don't enforce it strictly.
=> Support for properties passed to pure python gadgets etc,

gadgets/grappa/GrappaCalibrationBuffer.cpp, gadgets/grappa/GrappaWeightsCalculator.cpp, gadgets/interventional_mri/grappa_device.xml, toolboxes/core/cpu/math/hoNDArray_linalg.cpp, toolboxes/mri/pmri/gpu/htgrappa.cpp
Make posv single threaded, since it is found to be not thread-safe when using with openblas and cuda.
Speed up the rt grappa by allowing AHA to be computed with multi-threading. 
If no uncombined channel, the cpu kernel is computed from first target_coil_ channel. The reason is other channels are zeros after coil compression.
=> Fix rt grappa cpu test

toolboxes/core/cpu/math/hoNDArray_linalg.cpp, toolboxes/mri/pmri/gpu/htgrappa.cpp
Actually it is a bad idea to set number of threads to be 1 in the posv call itself. The reason is that posv call can be inside openmp loop. Depending the outloop openmp thread scheduling, some posv call will find num_threads to be 1 and after leaving the posv call, the number of threads will not be properly restored. This problem is found because after this change, some iterative code actually started to run with only one thread and becomes much slower.
It seems still better to handle the gpu/openblas posv threading problem at  where it happens, instead of changing basic linalg implementation.
=> revert the set_num_threads(1) in posv

gadgets/dicom/CMakeLists.txt
=> adds libiconv as a link dependency for DCMTK 3.6.1 on OS X

apps/gadgetron/GadgetStreamController.cpp, apps/gadgetron/GadgetStreamInterface.h, apps/gadgetron/main.cpp, gadgets/dicom/DicomFinishGadget.h, toolboxes/log/log.cpp, toolboxes/log/log.h
PR includes four distinct commits:
1. Fixed incorrect log output messages.
2. Added ability to redirect stdout to file specified in environment variable GADGETRON_LOG_FILE. Redirection is done in construction of singleton GadgetronLogger, and no changes are made if GADGETRON_LOG_FILE does not exist in the calling environment. This features is particularly useful in daemonizing a gadgetron instance.
3. Switched to recursive directory creation for Gadgetron workingDirectory, in case the parent of a specified workingDirectory does not exist. Uses BOOST's recursive creating function instead of non-recursive function.
4. Modified DicomFinishGadget to separate message creation from message sending. This allows subclasses with customized sending functionality, e.g. direct storage to a C-STORE …
=> bug fix  and new features

apps/gadgetron/main.cpp
The usage of `boost::filesystem::create_directories` is incorrect in Gadgetron's
`main.cpp`. This function returns `true` if the directory was created and `false`
otherwise. Not creating the directory is not an error, however, e.g. if it already
exists. In the case of an actual error this function throws a `boost::filesystem_error`.
Without this fix, it doesn't appear to be possible to run successive instances
of the Gadgetron since the temporary directory is not "cleaned up".
=> Fixing usage of boost::filesystem::create_directories

gadgets/gtPlus/GtPlusReconGadget.cpp, gadgets/gtPlus/config/GT_3DT_Cartesian.xml, gadgets/gtPlus/config/GT_3DT_Cartesian_GFactor.xml
Fix a bug in computing 3D slice orientation.
Since there are still problems with iterative coil map estimation, switch back to non-iterative version for now.
3D recon uses true 3D coil map estimation.
=> further fix 3D recon for image orientation

apps/gadgetron/gadgetron.xml.example, apps/gadgetron/gadgetron_xml.cpp, apps/gadgetron/gadgetron_xml.h, apps/gadgetron/main.cpp, apps/gadgetron/schema/gadgetron.xsd, gadgets/gtPlus/GtPlusReconGadget.cpp, toolboxes/cloudbus/CMakeLists.txt, toolboxes/cloudbus/CloudBus.cpp, toolboxes/cloudbus/CloudBus.h, toolboxes/cloudbus/cloudbus_io.h, toolboxes/cloudbus/cloudbus_main.cpp, toolboxes/cloudbus/cloudbus_relay.cpp
This is a reworked version of the cloudbus that now uses a relay to overcome the problems with multi-casting on many common cloud platforms. 
Basically, you would start the "gadgetron_cloudbus_relay" on some server and then set the relay address in the config file (gadgetron.xml):
<cloudBus>
<relayAddress>127.0.0.1</relayAddress>
<port>8002</port>
</cloudBus>
If the relay shuts down, the nodes will reconnect if and when the relay comes back up. The available nodes can be queried with the same interface function as the previous relay. 
@xueh2, I need you to check if this is compatible with the cloud stuff in gtplus. If so, I say we merge this and then we can add more bells and whistles as we go. 
Another question is if we need a script (or two) to start this from the chroot image, and …
=> New Cloudbus with Relay

gadgets/dicom/DicomFinishGadget.cpp
moved *key.set(0x0018, 0x0091)* outside of if statement so the else will effect echoTrainLength key instead of magnetic field strength key.
=> Fixed bug where empty echo Train length set Magnetic Field Strength to 1

apps/clients/gadgetron_ismrmrd_client/gadgetron_ismrmrd_client.cpp, gadgets/mri_core/MRIImageWriter.h
After reviewing related compoments, it is found that since MRIImageReader and ISMRMRD utilities support RO/E1/E2/CHA image, the gadgetron image writer and client are updated to support image with [RO E1 E2 CHA]. So now a gadget can send multi-channel images back to client.
I will make another PR to make IceGadgetron support multi-channel incoming images and run scanner  test on it.
=> fix the framework to be consistently support ROE1E2CHA

gadgets/mri_core/AcquisitionAccumulateTriggerGadget.h, gadgets/mri_core/BucketToBufferGadget.h, toolboxes/mri_core/CMakeLists.txt, toolboxes/mri_core/mri_core_acquisition_bucket.h, toolboxes/mri_core/mri_core_data.h
Split acquisition bucket into its own header.
Add constructors for SamplingLimit and SamplingDescription, so their member variables are initialized.
=> Acquisition bucket header

gadgets/gtPlus/GtPlusAccumulatorWorkOrderTriggerGadget.cpp, gadgets/mri_core/AsymmetricEchoAdjustROGadget.cpp, gadgets/mri_core/BucketToBufferGadget.cpp, gadgets/mri_core/BucketToBufferGadget.h, gadgets/mri_core/CMakeLists.txt, gadgets/mri_core/GenericCartesianGrappaReconGadget.cpp, gadgets/mri_core/GenericCartesianGrappaReconGadget.h, gadgets/mri_core/GenericCartesianReconReferencePrepGadget.cpp, gadgets/mri_core/GenericCartesianReconReferencePrepGadget.h, gadgets/mri_core/Generic_Cartesian_Grappa_T2W.xml, gadgets/mri_core/RemoveROOversamplingGadget.cpp, toolboxes/gtplus/workflow/gtPlusISMRMRDReconUtil.h, toolboxes/mri_core/mri_core_data.h, toolboxes/mri_core/mri_core_utility.cpp, toolboxes/mri_core/mri_core_utility.h
A single recon gadget for grappa is added.
An example is given for T2W data, Generic_Cartesian_Grappa_T2W.xml, which works with integration test data meas_MID00057_T2w.dat
The changes on BucketToBufferGadget are still needed to make sure kspace is buffered in the correct location. This PR includes the changes in PR #204.
Please focus on the main gadget GenericCartesianGrappaReconGadget
The recon kernel and other status is stored in GenericCartesianGrappaReconObj for every encoding space. Therefore, the incoming reconbit without ref data can be processed with buffered kernel and coil maps.
The recon chain consists of 
a) ensure the recon image to have squared pixel, therefore zero-padding resizing is not needed for E1. This avoids ringing in the final images. 
b) prepare the ref data. …
=> Single recon gadget

test/integration/get_data.py
small changes for Python 3 compatibility.  It should support all Python versions >= 2.6.  I tested it with both Python 2.7 and Python 3.4.
Using the newer "as" form of the exception clauses as done here breaks compatibility for Python versions older than 2.6 (which was released in 2008).
=> add python 3 support to get_data.py

apps/standalone/cpu/gtplus/CMakeLists.txt, apps/standalone/cpu/gtplus/Matlab_compute_coil_map_2D.cpp, apps/standalone/cpu/gtplus/Matlab_compute_coil_map_3D.cpp
I noticed that there are Matlab wrappers to the 2D and 3D coil map estimation routines in the codebase, but that these are not being built.  I added them to CMakeLists.txt and fixed a few namespace inconsistencies so that they build successfully.
After this, the build completes and I can find the MEX files in my build directory, but they do not seem to automatically end up in /usr/local/gadgetron/ after "make install", so perhaps I missed another necessary change somewhere?  I have very little familiarity with CMake.
Unfortunately, my Matlab installation is a bit outdated/broken at the moment and I get some library version conflicts when I try to actually call the routines, so I was unable to verify that they are working properly:
```
Invalid MEX-file …
```
=> WIP: fixing Matlab coil map wrappers

test/integration/run_all_tests.py, test/integration/run_gadgetron_test.py, test/unit/run_unit_tests.py
As suggested in #224, the first commit here fixes some `print` statements in run_gadgetron_test.py, so it is also python 3 compatible.  The other .py files in the `tests` folder were already python 3 compatible.
Various minor PEP8/formatting changes are in a separate, second commit so you can easily omit those if you don't want them for some reason.  The only thing I didn't address were lines with length > 80 characters.
=> python 3 compatibility for run_gadgetron_test.py

toolboxes/mri_core/mri_core_coil_map_estimation.cpp
This fixes what I believe is a bug in the 3D iterative coil map routine.  I believe the intent of the `sum_over_dimensions``  line modified here, was to sum all non-channel dimensions.  There was a reshape of via ``dataByCha`` to facilitate this but the reshaped array isn't used in the subsequent call.
Also, I made a simple python based implementation of this same iterative coilmap estimation that I am willing to contribute to https://github.com/ismrmrd/ismrmrd-python-tools if there is interest.  It would complement the Walsh method that is already implemented there.
=> BUG: wrong variable name in coil_map_3d_Inati_Iter

gadgets/mri_core/BucketToBufferGadget.cpp, gadgets/mri_core/GenericCartesianGrappaReconGadget.cpp, gadgets/mri_core/NoiseAdjustGadget.cpp
Add checking for empty noise co-variance matrix
Add handling in BucketToBufferGadget for the absence of parallel imaging section in protocol
Fix make_ref_coil_map function in grappa gadget to ensure the image sizes of ref_coil_map agree with recon_size
=> Fix philips data recon

apps/gadgetron/GadgetServerAcceptor.cpp, apps/gadgetron/GadgetServerAcceptor.h, apps/gadgetron/main.cpp, toolboxes/cloudbus/CMakeLists.txt, toolboxes/cloudbus/CloudBus.cpp, toolboxes/cloudbus/CloudBus.h, toolboxes/cloudbus/cloudbus_io.h, toolboxes/cloudbus/cloudbus_relay.cpp, toolboxes/rest/gadgetron_rest.h
This commit adds ReST API to the cloudbus_relay. This is needed/useful for orchestrating a large number of nodes in the cloud that scale dynamically based on workload. For instance, you can query the cloud_relay to see what nodes are available and some statistics:
curl http://localhost:18002/info/json
which could return something like this:
````
{"nodes":[{"active_reconstructions":0,"rest_port":9080,"port":9002,"last_recon":3.02057,"address":"127.0.0.1","compute_capability":1,"uuid":"f027b732-afe7-4f42-b9f5-1d0a9b34e959"},{"active_reconstructions":0,"rest_port":18003,"port":9004,"last_recon":1.4479e+09,"address":"127.0.0.1","compute_capability":1,"uuid":"defcbf2e-3e2a-4f5d-94e1-2717b427b440"}],"number_of_nodes":2}
````
So in this case we have two active nodes. Or
```` …
```
=> Rest cloud

test/cuNDArray_utils_test.cpp
In CUDA7.5, tests failed:
[ RUN      ] cuNDArray_utils_TestReal/0.meanTest
/home/xueh2/mrprogs/gadgetron/test/cuNDArray_utils_test.cpp:111: Failure
Value of: mean(&this->Array)
Actual: 12.340011
Expected: v1
Which is: 12.34
[  FAILED  ] cuNDArray_utils_TestReal/0.meanTest, where TypeParam = float (1 ms)
[ RUN      ] cuNDArray_utils_TestCplx/0.padTest
/home/xueh2/mrprogs/gadgetron/test/cuNDArray_utils_test.cpp:222: Failure
Value of: imag(mean(&this->Array))
Actual: 56.780022
Expected: imag(mean(out.get()))*scale
Which is: 56.779968
[  FAILED  ] cuNDArray_utils_TestCplx/0.padTest, where TypeParam = Gadgetron::complext<float> (7 ms)
=> adjust ut threshold to make the test pass in CUDA7p5

apps/gadgetron/GadgetServerAcceptor.cpp, apps/gadgetron/GadgetServerAcceptor.h
This PR adds a url or querying the port of the running gadgetron. Will return a 500 server error response when the acceptor is closed. 
```
$ curl http://localhost:9080/info/port
9002
```
If the acceptor is closed:
```
$ curl http://localhost:9080/acceptor/close
Acceptor closed
$ curl http://localhost:9080/info/port
Port not available
```
=> Added an info/port path to the ReST API.

apps/clients/gadgetron_ismrmrd_client/gadgetron_ismrmrd_client.cpp
This timeout option is important since some automated uses of the client will hang for a long time (integration tests or use of the client on a scanner), if a connection cannot be made. 
This is a bit of an ugly way of creating a connection timeout on the client. The connect(...) function on the tcp::socket in boost::asio does not have a timeout option. The asynch_connect(...) should be used instead, but that would require some more reworking of the client, so we have to create our own timeout. It is done with wait on a condition variable.
@xueh2 Please take a careful look at this. I think this is what is needed. Could you also just give it a quick check compiling on Windows.
=> Added timeout to gadgetron_ismrmrd_client. Defaults to 10 seconds

toolboxes/python/python_hoNDArray_converter.h
This patch allows compilation with Numpy 1.6.
=> add work-around for Numpy 1.6 compatibility

toolboxes/plplot/ut/CMakeLists.txt, toolboxes/plplot/ut/plplot_test.cpp
This avoids linking problems with boostPython on some systems.
=> remove dependency on boost libraries in plplot test.

cmake/FindCUDA_advanced.cmake
Signed-off-by: Zhitao Li zhitaoli@email.arizona.edu
This closes #227, since cmake 3.3 they added a new option to allow people to use static CUDA lib, and by default this option is been turned on, and that's why it is returning different result.
This pull request adds a single line to set this value to false, before calling find_package(CUDA 5.5), and that fixed our problem.
The option is still available on the UI under CUDA, it's called CUDA_USE_STATIC_CUDA_RUNTIME, but using static lib is going to cause problems.
=> Change default CUDA_USE_STATIC_CUDA_RUNTIME value to false

gadgets/mri_core/CMakeLists.txt, gadgets/mri_core/IsmrmrdDumpGadget.cpp, gadgets/mri_core/IsmrmrdDumpGadget.h
A folder can be added to the ISMRMRD dump file name and the folder will be created if it does not exist. Measurement ID is also added to the filename. 
@xueh2, can you check if this does the trick for the data saving?
=> Added folder and measurement ID to IsmrmrdDumpGadget

docker/create_chroot_from_image.sh, docker/tag_image_with_version.sh
This scrip can be used to make a chroot (tar.gz) from a docker image. Usage:
docker/create_chroot_from_image.sh gadgetron/ubuntu_1404_no_cuda
@xueh2, do you think this is a reasonable start?
=> Added scrip for packaging up a chroot image from a docker container

docker/create_chroot_from_image.sh
with the -t, buildbot calls for create_chroot_from_image.sh returns with error
"cannot enable tty mode on non tty input"
Need to remove "-t" to fix this.
=> fix docker making packaged called in buildbot

gadgets/mri_core/GenericReconCartesianReferencePrepGadget.cpp, gadgets/mri_core/GenericReconCartesianReferencePrepGadget.h, gadgets/mri_core/Generic_Cartesian_Grappa.xml, gadgets/mri_core/Generic_Cartesian_Grappa_EPI.xml, gadgets/mri_core/Generic_Cartesian_Grappa_RealTimeCine.xml, gadgets/mri_core/Generic_Cartesian_Grappa_T2W.xml
Often, if it is in no acceleration mode, no ref data is acquired. So in this case, it is necessary to use the imaging data as ref.
Add a control to only set ref once for the first incoming IsmrmdReconData. So it can avoid unnecessary coil map estimation in the recon step.
=> add more controls for ref preparation in generic recon

gadgets/epi/CMakeLists.txt, gadgets/epi/EPIReconXGadget.cpp, gadgets/epi/EPIReconXGadget.h, gadgets/epi/FFTXGadget.cpp, gadgets/epi/FFTXGadget.h, gadgets/epi/OneEncodingGadget.cpp, gadgets/epi/OneEncodingGadget.h, gadgets/mri_core/CMakeLists.txt, gadgets/mri_core/GenericReconCartesianGrappaGadget.cpp, gadgets/mri_core/GenericReconCartesianReferencePrepGadget.cpp, gadgets/mri_core/GenericReconEigenChannelGadget.cpp, gadgets/mri_core/GenericReconEigenChannelGadget.h, gadgets/mri_core/GenericReconFieldOfViewAdjustmentGadget.cpp, gadgets/mri_core/GenericReconGadget.cpp, gadgets/mri_core/GenericReconImageArrayScalingGadget.cpp, gadgets/mri_core/GenericReconKSpaceFilteringGadget.cpp, gadgets/mri_core/GenericReconPartialFourierHandlingGadget.cpp, gadgets/mri_core/Generic_Cartesian_Grappa_EPI_AVE.xml, toolboxes/mri/epi/EPIReconXObjectFlat.h, toolboxes/mri/epi/EPIReconXObjectTrapezoid.h
Make EPI reconx data driven, so it is more robust for FLASH ref line cases
Speedup EPI correction by calling gemm and avoiding some memory allocation
Add more timing in generic chain gadgets
Add a OneEncodingGadget to make EPI with flash ref line works with generic chain
Add a Generic_Grappa_EPI_AVE.xml to trigger EPI recon by average
=> Epi generic chain

gadgets/mri_core/BucketToBufferGadget.cpp
It is incorrect "NE0 = encoding.reconSpace.matrixSize.x", since recon matrix size is independent from encoded matrix size. 
It is fixed to use the incoming data sample length.
=> fix the NE0 assignment in BucketToBufferGadget

gadgets/mri_core/FFTGadget.cpp, gadgets/mri_core/SimpleReconGadget.cpp
The k-space data needs to be centered before applying ifft.
It affects:
-FFTGadget.cpp
-SimpleReconGadget.cpp
=> Fixed bug in iFFT reconstruction

gadgets/mri_core/CMakeLists.txt, gadgets/mri_core/GenericReconCartesianSpiritGadget.cpp, gadgets/mri_core/GenericReconCartesianSpiritGadget.h, gadgets/mri_core/Generic_Cartesian_Spirit.xml, toolboxes/mri_core/mri_core_spirit.cpp
Add linear spirit gadget into the generic chain
a) Both 2D and 3D linear spirit was implemented
b) Add Generic_Cartesian_Spirit.xml for spirit reconstruction
c) This linear spirit gadget will serve as basis for further nonlinear spirit reconstruction.
d) Integration test cases to be added in next PR.
=> add linear spirit recon gadget for generic chain

gadgets/mri_core/BucketToBufferGadget.cpp, gadgets/mri_core/GenericReconCartesianGrappaGadget.cpp, gadgets/mri_core/GenericReconCartesianSpiritGadget.cpp, gadgets/mri_core/GenericReconCartesianSpiritGadget.h, gadgets/mri_core/GenericReconEigenChannelGadget.cpp, gadgets/mri_core/GenericReconGadget.cpp, gadgets/mri_core/GenericReconGadget.h
A few fix and refactoring before the nl spirit:
a) Fix output messages in BueckerToBufferGadget
b) Pull SNR unit scaling computation as a member function into GadgetronReconGadget, as it is useful for all recon algorithms
c) Pull coil combination code as a member function in linear spirit gadget, as the same code pieces are used also for nl spirit
d) Adjust the print out messages at GenericReconEigenChannelGadget
=> fix_bugs_refactoring_generic_chain

gadgets/mri_core/GenericReconGadget.cpp
fix two warnings found in mac compilation
=> fix two warnings found in mac

docker/incremental/ubuntu_1404_cuda55/Dockerfile, docker/incremental/ubuntu_1404_cuda75/Dockerfile, docker/incremental/ubuntu_1404_no_cuda/Dockerfile
Added the ability to control the gadgetron log file location in the container. 
The reason for this is that having it directly in `/tmp` can be problematic when tmp is mounted from outside the container and `/tmp/gadgetron` is mounted from outside the container too. One mount can shadow the other and it is not completely well defined (or at least not guaranteed) what the order is.
=> Added ability to control log file location in Docker container

gadgets/distributed/DistributeGadget.cpp, gadgets/distributed/DistributeGadget.h, gadgets/mri_core/Generic_Cartesian_NonLinear_Spirit_RealTimeCine_Cloud.xml
in this mode (default) nodes receive data sequentially, e.g. slice 1 to node 1, once slice 2 arrives, it is assumed that slice 1 is done. This allows the distribute Gadget to send a close down the pipe and trigger recon and clean up.
@xueh2 could you please verify that this now has the correct behavior?
=> Added sequential node usage to DistributeGadget,

toolboxes/solvers/sbSolver.h, toolboxes/solvers/sbcSolver.h
OUTPUT_MAX is supposed to be the size of the output_mode_ enum, so output_mode_ cannot have that value.  Replace it for OUTPUT_VERBOSE instead.
=> Fixed checking for OUTPUT_MAX

toolboxes/mri_core/mri_core_kspace_filter.cpp
Make sure the center of the filter is 1 (currently, it was 0).
=> Fixed bug in Tapered Hanning filter

toolboxes/cmr/CMakeLists.txt, toolboxes/cmr/cmr_kspace_binning.cpp, toolboxes/cmr/cmr_kspace_binning.h, toolboxes/cmr/cmr_motion_correction.cpp, toolboxes/cmr/cmr_motion_correction.h, toolboxes/cmr/cmr_spirit_recon.cpp, toolboxes/cmr/cmr_spirit_recon.h
a) Complete the first version of kspace binning
b) The schemes of interpolating deformation field and solving moco recon equation are not implemented; but places are left to add them later
c) Add a cmr_spirit_recon.h/.cpp, implementing some functionalities commonly used in cmr applications for spirit recon
Next step is to build gadget.
=> add kspace binning recon linear and nonlinear

gadgets/mri_core/PhysioInterpolationGadget.cpp
scanner test found physio interp images cannot be loaded into the exam card segments
this is for physio interp image numbering fix to make sure image number start from 1 and increasing
=> fix the image numbering in physio interp

gadgets/mri_core/GenericReconCartesianNonLinearSpirit2DTGadget.cpp
fix a bug in NL spirit
if multi-S array is input into recon, but all S are combined to generate one set of coil map, then this check is needed to prevent memory exception
=> fix a bug for multi-S NL spirit

gadgets/mri_core/CMakeLists.txt, gadgets/mri_core/CoilSenMapGadget.cpp, gadgets/mri_core/CoilSenMapGadget.h, gadgets/mri_core/DependencyDataSenderGadget.cpp, gadgets/mri_core/DependencyDataSenderGadget.h, gadgets/mri_core/config/default_measurement_dependencies_Noise_CoilSen_SCC.xml, toolboxes/mri_core/CMakeLists.txt, toolboxes/mri_core/mri_core_dependencies.cpp, toolboxes/mri_core/mri_core_dependencies.h
add gadgets to save incoming coil map data or surface coil correction pre scan.
add default_measurement_dependencies_Noise_CoilSen_SCC.xml to allow process noise, saving coil map or scc dependency data
same naming convention like dependent noise is used. e.g. a saved SCC data is GadgetronSCCMap_41548_21533254_21533259_298
This PR will be used for further sense gadget and SCC gadget with generic chain.
=> Coil sen dependency

cmake/FindGadgetron.cmake
Set GADGETRON_INSTALL_CONFIG_PATH in FindGadgetron.cmake to enable installation of new libraries configuration file.
=> [issue#448] set GADGETRON_INSTALL_CONFIG_PATH

apps/gadgetron/Gadget.h, gadgets/epi/CMakeLists.txt, gadgets/epi/EPICorrGadget.cpp, gadgets/epi/EPIPackNavigatorGadget.cpp, gadgets/epi/EPIPackNavigatorGadget.h, gadgets/matlab/BaseBufferGadget.m, gadgets/matlab/MatlabBufferGadget.cpp, gadgets/matlab/MatlabBufferGadget.h, gadgets/mri_core/AcquisitionAccumulateTriggerGadget.cpp, test/integration/run_gadgetron_test.py, toolboxes/matlab/CMakeLists.txt, toolboxes/matlab/MatlabUtils.cpp
Here's a second attempt for PR #463.
Note that I have modified test/integration/run_gadgetron_test.py to incorportate John Roberts' technique for allowing co-existence of Matlab and Python in integration testing.
...from the gadgetron google group discussion thread:
Rely on Ubuntu's library search management
Unset LD_LIBRARY_PATH
Add zzzzzzzzzzzzmatlab.conf to /etc/ld.so.conf.d/ with contents /opt/matlab/bin/glnxa64.  The Zs in the name force the matlab search path to be appended at the very end of the system search path.
ldconfig - reset the system library search path to cache the new path including matlab
All current integration tests pass for me.
Oliver
=> Matlab buffer gadget and epi navigator packing

gadgets/epi/EPICorrGadget.cpp, gadgets/epi/EPICorrGadget.h
I have included a new option for the EPICorrGadget: you can now filter the navigator parameters over repetitions to get a more robust navigator correction.
For now, the filtering is a weighted linear fit of the corresponding navigator parameter from the last few volumes.  The exact number of volumes to use for the filtering is a gadget property.  It can be set to zero (or a negative number) to turn the filtering off.  If you want to exclude a few initial volumes to allow for the reach of a steady state, you can specify that too.  The weights for the linear fit are the average (across coils and across the RO dimension) magnitude of one of the navigators.
In principle, because of noise in the data, our estimates of the navigator parameters (e.g., B0 mean and slope, Odd-Even correction mean …
=> EPI navigator parameter filtering

gadgets/mri_core/GenericReconGadget.cpp
Parallel imaging parameters from the first encoding space were
originally used for all encoding spaces.
=> Fixed parallel imaging parsing for additional encoding spaces

gadgets/mri_core/GenericReconBase.cpp, toolboxes/image_io/CMakeLists.txt, toolboxes/image_io/ImageIOAnalyze.h
Summary: In GenericReconBase::process_config, create debug_folder if it doesn’t exist.  Also verify folder existence prior to writing files in ImageIOAnalyze.
Discussion: Boost is used to provide easy cross-platform I/O functions, but this also means that boost is required for mri_core.
=> Sanity checks for debug_folder

toolboxes/cmr/cmr_parametric_mapping.cpp
for ill-posed data points, compute sd may throw exceptions; do not stop computation for these pixels.
=> Further map sd fix

gadgets/bart/bartgadget.cpp
Added minor hack to circumvent the false-positive return boolean value of boost::filesystem::create_directories() version 1.58.0.1. 
Note: This bug was fixed in boost version 1.61.0 and higher
=> Thread safe version of bart gadget (v2)

gadgets/dicom/dicom.xml
constant_noise_variance not deleted in dicom.xml yet - removed in all other xmls in previous commits
=> Remove obsolete property

gadgets/bart/bartgadget.cpp, gadgets/bart/bartgadget.h
Hi,
working with the BART Gadget, I figured out two problems:
1. platform dependent line endings of the BART Shell Script (gadgets/bart/Sample_Grappa_Recon.sh) leads to wrong file names for BART. I am working on a Linux based machine, but the line endings of the script are Windows style, wich leads to the fact that BART tries to load files named e.g. "maps\r.cfl".
Trimming the command line in the Gadget from both sides solves the problem for me.
2. The command line interpreter in the BART Gadget does not cope with inline comments. This is especially important when the output filename is determined.
Cropping the line is a simple solution, but obviously does not handle cases like:
`\#no comment`
or
`"#nocomment"`
Best regards,
Fabian
=> BART Gadget improvements

gadgets/bart/bartgadget.cpp
Enabled parallel imaging does not automatically mean that a encoding step is >1,
so only search for value if the encoding step is >1.
=> BART-Gadget improvement: Condition relating acceleration changed

apps/gadgetron/GadgetStreamController.cpp, apps/gadgetron/GadgetStreamController.h, apps/gadgetron/GadgetStreamInterface.h, apps/gadgetron/gadgetron_xml.cpp, apps/gadgetron/gadgetron_xml.h, apps/gadgetron/main.cpp, gadgets/distributed/DistributeGadget.cpp, gadgets/distributed/DistributeGadget.h
The buffer allocated on line 222 in GadgetStreamController.cpp has an unreachable matching delete. Config files read from the filesystem were leaked by every chain. 
Cleanup involves the use of streams over strings, and saving the deserialized object in stead of raw strings (avoids later re-deserialization).
Tested on Fedora 28. I had some trouble with some unrelated python test cases, but I'm not too concerned as they also fail when I test current master.
=> Fixing a leak and cleaning up GadgetStreamController configuration.

apps/gadgetron/GadgetStreamController.cpp
GadgetStreamController service thread marked as joinable, but never joined, leading to zombie threads.
Tested on Fedora 28; everything looks well.
=> Fixing GadgetStreamController zombie thread.

gadgets/mri_core/RemoveROOversamplingGadget.cpp
use pre-allocated array to speed up RemoveROOversamplingGadget
=> fix RemoveROOversamplingGadget.cpp for better mem usage

test/CMakeLists.txt, test/node_discovery_test.cpp, toolboxes/CMakeLists.txt, toolboxes/cloudbus/CMakeLists.txt, toolboxes/cloudbus/CloudBus.cpp, toolboxes/node_discovery/CMakeLists.txt, toolboxes/node_discovery/examples/node_list.json, toolboxes/node_discovery/node_discovery.cpp, toolboxes/node_discovery/node_discovery.h, toolboxes/node_discovery/node_discovery_export.h
Adding `node_discovery` toolbox and tests. 
Toolbox is used in CloudBus when `GADGETRON_NODEDISCOVERY` environment is set. 
Closes #656
=> basic node discovery implementation

docker/start_supervisor, toolboxes/denoise/non_local_bayes.cpp
This pull request optimizes the non local Bayes method by avoiding some slow parts of std::complex, assigning better OMP settings and loading all patches at the beginning.
=> Optimized non local Bayes, and set relevant OMP options

docker/base/ubuntu_1604/Dockerfile, docker/base/ubuntu_1604_cuda80_cudnn6/Dockerfile, docker/base/ubuntu_1604_cuda80_cudnn7/Dockerfile, docker/base/ubuntu_1604_cuda90_cudnn7/Dockerfile, docker/base/ubuntu_1604_cuda92_cudnn7/Dockerfile, docker/base/ubuntu_1804/Dockerfile, docker/base/ubuntu_1804_cuda90/Dockerfile, docker/base/ubuntu_1804_cuda92_cudnn7/Dockerfile, gadgets/CMakeLists.txt, gadgets/bart/BART_Recon.xml, gadgets/bart/BART_Recon_cloud.xml, gadgets/bart/BART_Recon_cloud_Standard.xml, gadgets/bart/CMakeLists.txt, gadgets/bart/Sample_Grappa_Recon.sh, gadgets/bart/Sample_Grappa_Recon_Standard.sh, gadgets/bart/bart_helpers.cpp, gadgets/bart/bart_helpers.h, gadgets/bart/bart_logger.cpp, gadgets/bart/bartgadget.cpp, gadgets/bart/bartgadget.h, test/integration/CMakeLists.txt
Due to recents update to BART, it is now possible to embed BART more easily into other projects. This PR is to better integrate BART within Gadgetron.
----
Due to the way the new implementation is done, there are a few breaking changes for users of `BartGagdet`. These are all due to the removal of a couple of properties of `BartGadget` which do not make sense anymore:
- `isBartFolderBeingCachedToVM`
- `AllocateMemorySizeInMegabytes`
One possible workaround would be to have the config parser ignore them with an appropriate warning message, but I don't know if that at all possible with Gadgetron as of now and did not look into it.
One big changes due to the embedding of BART into Gagdetron is that now the BART sources need to be compiled at the same time as Gadgetron. [1]
For people with …
=> Bart embedding

gadgets/bart/bart_logger.cpp, gadgets/bart/bartgadget.cpp, gadgets/bart/bartgadget.h
Fix "Unable to open recon script error"
Remove unused parameter
Replace deprecated C++ header
Remove unnecessary copied parameters
Remove redundant class member initialization
Remove "compare" to test equality of strings
Use more effective overload function
=> Fix Unable to open Recon script error

toolboxes/mri_core/mri_core_coil_map_estimation.cpp
bug occurred only if OPENMP is off
=> fix GadgetronTimer include in mri_core_coil_map_estimation

gadgets/python/gadgets/image_viewer.py
fixed to work but only test on Ubuntu 18.04 with BUILD_WITH_PYTHON3=ON 
As Gtk+matplotlib has too much choice variant,  it's not easy to choose the right combination, not only this,  python2/python3,  PyGTK/PyGObject, GTK with/without Cairo all has its own history and compatible problem, a clearly workable one may be better for user
ref:
https://matplotlib.org/faq/usage_faq.html?highlight=backend
https://matplotlib.org/gallery/user_interfaces/embedding_in_gtk3_panzoom_sgskip.html
https://matplotlib.org/users/navigation_toolbar.html
=> minor fix for ubuntu 18.04

cmake/FindPLplot.cmake
We failed to find the PLplot libraries on Fedora, when installed. This is a quick fix. 
There's probably a better way to get this done, but it's not worse than the old code, so it still feels like an upgrade.
=> Fixed PLplot cmake issue on Fedora.

gadgets/mri_core/AcquisitionAccumulateTriggerGadget.cpp, gadgets/mri_core/RateLimitGadget.h
For n_acquisitions trigger, target was "stuck" on initial value.
Copy / paste error in RateLimitGadget.
=> Fix ongoing acquisitions trigger (+ typo)

doc/source/conf.py
Steps to reproduce:
Open a terminal
Go into gadgetron build directory
Launch the following commands:
cmake -DBUILD_DOCUMENTATION=On ..
make
Result:
The documentation build does not succeed because of this error:
Sphinx error:
master file /home/aymeric/Workspace/gadgetron-github/doc/source/contents.rst not found
doc/CMakeFiles/Sphinx.dir/build.make:57: recipe for target 'doc/CMakeFiles/Sphinx' failed
Expected result:
Documentation is built without any error.
Reason & Solution:
https://stackoverflow.com/questions/56336234/build-fail-sphinx-error-contents-rst-not-found
=> Fix sphinx documentation

gadgets/mri_core/CMakeLists.txt, gadgets/mri_core/CoilComputationGadget.cpp, gadgets/mri_core/CoilComputationGadget.h
This is meant to be used as an interface to Gadgetron to access its coil computation capabilities.
It simply applies the  `coil_map_Inati` method to a set of image data that are provided in the form of uncombined reconstructions.
This allows to define the inverse Fourier transform outside of Gadgetron itself but still couple to it and extract the coilmap features.
=> Added Gadget to compute coilmaps from image data

CMakeLists.txt, apps/gadgetron/CMakeLists.txt, apps/gadgetron/connection/stream/Stream.cpp, apps/gadgetron/initialization.cpp, apps/gadgetron/initialization.h, apps/gadgetron/main.cpp, core/CMakeLists.txt
Made a few changes, most related to getting Gadgetron to package for Debian/Ubuntu. 
Most notably, I'm detecting the use of OpenBLAS, and forcing the number of pthreads available to OpenBLAS internally to one. This has no effect when OpenBLAS is compiled for OpenMP, and it prevents several threading issues when OpenBLAS is compiled for pthreads (as on Ubuntu). 
I saw no degradation of performance when running the test suite.
=> Ubuntu packaging

core/writers/ImageWriter.cpp
This breaks UTF8, but is required for backwards compatibility
=> Reverted a fix in how we're sending Metaattributes.

core/writers/ImageWriter.cpp
Fixing issue caused by 1-byte meta-strings when sending meta-less images.
This (presumably) caused a number of errors like this:
```
terminate called after throwing an instance of 'std::runtime_error'
what():  Unable to load ISMRMRD Meta XML document
```
=> Fixing issue caused by 1-byte meta-strings when no meta is present.

toolboxes/core/cpu/hoNDArray.hxx
The second and third arguments in the call to `std::copy_n` should be exchanged. I think this error arised when switching from `memcpy`, which takes arguments in a different order.
=> Fix a bug in hoNDArray::get_sub_array

toolboxes/nfft/cpu/CMakeLists.txt
I realised attempting to link against `libgadgetron_mri_noncartesian` (which resulted in dlerror) that hoNFFTOperator was undefined. Hopefully this will solve the issue.
=> Fix for undefined hoNFFTOperator

test/integration/run_gadgetron_test.py
Test script compared megabytes (as specified in the test config) to number of bytes available on system. Obviously, this caused the skipping based on memory to frequently fail.
=> Fixed issue where test script would never skip tests due to insufficient system memory.

gadgets/dicom/dicom_ismrmrd_utility.cpp, gadgets/dicom/dicom_ismrmrd_utility.h
The header and data contained in the GadgetContainerMessage must not be modified by the method write_ismrmd_image_into_dicom
=> Fix write_ismrmd_image_into_dicom

apps/clients/gadgetron_ismrmrd_client/gadgetron_ismrmrd_client.cpp
**Steps to reproduce**
- Use a Linux machine
- Disconnect your machine from internet
- Ensure the loopback device is the only network device with an address:
- open a terminal
- launch ifconfig
- check lo (loopback device) is the only network device which has an inet address (127.0.0.1)
- Follow the hellow world gadgetron tutorial: https://github.com/gadgetron/gadgetron/wiki/Gadgetron-Hello-World
**Result**
Nothing is received by gadgetron and gadgetron_ismrmrd_client caught this error:
"Error caught: resolve: Host not found (authoritative)"
**Expected Result**
Gadgetron Hello World works as described in the tutorial
**Reason**
tcp::resolver::query constructor uses boost::asio::ip::resolver_query_base::address_configured
as default value for the last parameter "resolve_flags".
In our case …
=> Fix gadgetron_ismrmrd_client when the loopback device is the only network device with an address

.devcontainer/.dockerignore, .devcontainer/.gitignore, .devcontainer/Dockerfile, .devcontainer/build-and-push-codespace-image.sh, .devcontainer/devcontainer.json, .devcontainer/get-current-image-digest.sh
This PR adds a [VS codespaces](https://visualstudio.microsoft.com/services/visual-studio-codespaces/) `.devcontainer` configuration to the code base. With this addition, it is possible to create a pre-configured codespace with all the tools setup and do Gadgetron development in either the browser or in VS code with full syntax highlighting, intellisense, etc.
Example of full IDE experience in the browser:
=> Codespaces devcontainer

gadgets/dicom/dicom_ismrmrd_utility.cpp
This function sets the encoding to Latin1 (ISO_IR 100) but utf-8 allows
to manage much more characters.
This function is used only in DicomFinishGadget which does not require
Latin1 encoding.
=> Fix fill_dicom_image_from_ismrmrd_header when utf-8 encoding is used.

test/gadgets/setup_gadget.h
This missing include does not cause compilation error because this header
is only included test/gadgets/AcquisitionAccumulateTrigget_test.cpp which
includes AcquisitionAccumulateTriggerGadget.h which includes Node.h.
=> add missing include in setup-gadget-header

toolboxes/mri/sdc/SDC.h, toolboxes/mri/sdc/SDC.hpp, toolboxes/mri/sdc/gpu/CMakeLists.txt, toolboxes/mri/sdc/gpu/cuSDC.cu, toolboxes/mri/sdc/gpu/cuSDC.h
Added the function template to estimate DCF with convolution types for cuNDArrays. 
Please note there are memory access errors with Atomic Mode that I was testing to be able to do DCF estimation for large data sets.
=> Updated SDC to enable atomic mode for DCF

test/integration/run_gadgetron_test.py
Explicitly request read-only access to h5 files in test script to squelch warning.
=> Silence warning emitted by test script.

apps/gadgetron/connection/stream/PureDistributed.cpp, apps/gadgetron/connection/stream/PureDistributed.h, apps/gadgetron/connection/stream/common/Discovery.cpp, apps/gadgetron/connection/stream/common/External.cpp, apps/gadgetron/system_info.cpp
* Fixed an issue where gadgetron would fail to detect IPv6 on newer platforms, leading to connection issues for workers.
* Fixed issue where PureDistributed would hang if no workers could be reached. 
* Improved error/warning output a little.
=> Fixed a few issues causing PureDistributed to hang on Fedora 33.

gadgets/mri_core/GenericReconCartesianGrappaGadget.cpp
let gmap be sent first if required, since some downstream application may expect gmap to be used with images
=> send out gmap first if required in generic chain

test/integration/cases/gpu_golden_radial_mode2_sb.cfg, test/integration/cases/gpu_spiral_sb.cfg, test/integration/run_tests.py
Ammending tags on sb tests - they were 'fast' when in fact they were not fast.
=> Fixing a few minor issues with the test script.

test/integration/cases/generic_grappa_snr_R1_PEFOV100_PERes100_compression.cfg, test/integration/run_gadgetron_test.py
Motivation: We are prepping a PR with some performance improvements to the compression. To make sure we don't break anything, we will be adding unit tests for the compression, but we would also like at least one end to end test that uses compression. This will give us some test coverage as we move the compression improvements in. 
Adds:
* Ability to add `additional_arguments` to the `gadgetron_ismrmrd_client` when running integration (e2e) tests. 
* Added test case that uses compression in a simple reconstruction.
=> E2E Compression Tests

docker/build_gadgetron_dependencies.sh, docker/install_ubuntu_dependencies.sh
This PR pins the version of (Python) `ismrmrd` to `1.9.5` since a recent problem in xsdata is causing issues. Version `1.9.5` of python-ismrmrd fixes the problem and pins the xsdata version.
=> Pinning ISMRMRD version

docker/install_ubuntu_dependencies.sh
Currently not building, and no test is available, so should be removed (#1034).
=> Remove ZFP

.devcontainer/Dockerfile
This is a leftover cleanup of the default image for the devcontainer.
=> Setting correct default base image for devcontainer

apps/clients/gadgetron_ismrmrd_client/CMakeLists.txt, gadgets/mri_core/CMakeLists.txt
The name of the variable is wrong (should be `HDF5_INCLUDE_DIRS`) and in any case it is obsolete as we use the `ISMRMRD` target now.
Fixes #1042
=> remove explicit include_directories of HDF5_INCLUDE_DIR

environment.yml
The issue raised in #1045 
Based on description by @dchansen, there could be a race condition when both Gadgetron and external process (e.g. Python) tries to load memkind (which it doesn't find in current images). 
This PR adds memkind and also updates MKL to 2022.0.1.
(sort of) fixes #1045
=> Addressing issue with race condition when MKL tries to load memkind

environment.yml, toolboxes/registration/optical_flow/gpu/cuResampleOperator.cu
This PR updates to CUDA 11.6 and switches to the nvidia channels for CUDA. There is a small workaround for the thrust namespace in one .cu file. This should build on GPU and non-GPU machines.
=> Update to CUDA 11.6

test/integration/run_gadgetron_test.py
Each integration test gets its own storage server process. Sometimes, when starting a new server immediately after tearing the old one down, the port can still appear to be in use.
I considered keeping the same storage server process alive for the entire test suite, but that would have required more extensive changes. Instead, we simply add some retries. 
Addresses #1079
=> Harden storage server process management in integration tests.

gadgets/mri_core/AsymmetricEchoAdjustROGadget.cpp, gadgets/mri_core/AsymmetricEchoAdjustROGadget.h
Continuing #1087, this PR updates AsymmetricEchoAdjustROGadget to a ChannelGadget, leaving the existing operational logic the same as much as possible. The only major change is that local method addPrePostZeros has been moved out of the Gadgetron namespace into the unnamed namespace. 
The new ChannelGadget accepts Core::Acquisition and outputs Core::Acquisition. 
One question: since usage in the existing codebase varies, should the output function be:
` out.push(Core::Acquisition{header, acq, traj});`
or 
` out.push(Core::Acquisition{std::move(header), std::move(acq), std::move(traj)});`
=> AsymmetricEchoAdjustROGadget -> ChannelGadget

core/CMakeLists.txt
Hi forks,
The IsmrmrdContextVariables.h need be installed, or the out of tree gadget build will be failed.
The MWE is https://github.com/medlab/gadgetron-4-fun/tree/main/gadgetron-cpp-demo/imagepassthroughgadget . 
The file is needed by Gadget.h, as  Gadget.h > Context.h > Storage.h > IsmrmrdContextVariables.h
Tks,
Cong
=> install IsmrmrdContextVariables.h

gadgets/mri_core/readers/GadgetIsmrmrdReader.h
Resubmitting this PR with **just** these changes.
Clang has an issue with the class destructor being marked as 'final', but the class itself not being marked in the same way.
Removing the 'final' designation on the class destructor also removed this error. However, the change as submitted in this PR seems more consistent with the original intent of the class being defined in the way it was.
=> Addresses '-Werror,-Wfinal-dtor-non-final-class' error with Clang build

core/readers/ImageReader.cpp
Functions are duplicately defined in 'core/io/ismrmrd_types.h'.  Suggesting removal here and possibly moving definitions in 'core/io/ismrmrd_types.h'?
=> Clang complains about 'ismrmrd_data_type' definitions not being used

azure-pipelines.yml
We have a problem that the CI builds often go beyond 60 minutes which is the default duration. This gives the pipeline plenty of time.
=> Extend pipeline timeout

gadgets/mri_core/AutoScaleGadget.cpp, gadgets/mri_core/AutoScaleGadget.h
Continuing #1087, this PR converts AutoScaleGadget to a PureGadget using the conventions established in #1090 and #1094.
=> AutoScaleGadget->PureGadget Conversion

toolboxes/core/cpu/image/hoNDImage.hxx, toolboxes/core/vector_td_utilities.h
Probably shouldn't have hoNDImage.h and hoNDImage.hxx including each other.
=> Minor white space clean-up, and removing recursive header inclusion.

gadgets/mri_core/ImageArraySplitGadget.cpp, gadgets/mri_core/ImageArraySplitGadget.h
Continuing #1087, this PR converts ImageArraySplitGadget to a ChannelGadget using the conventions established in #1090 and #1094.
=> ImageArraySplitGadget->ChannelGadget Conversion

gadgets/mri_core/ImageSortGadget.cpp, gadgets/mri_core/ImageSortGadget.h
Continuing #1087, this PR converts ImageSortGadget to a ChannelGadget using the conventions established in #1090 and #1094, with the cache containing Image objects instead of the header pointers.
=> Convert ImageSortGadget to ChannelGadget

gadgets/mri_core/RemoveROOversamplingGadget.cpp, gadgets/mri_core/RemoveROOversamplingGadget.h
Continuing #1087, this PR converts RemoveROOversamplingGadget to a ChannelGadget using the conventions established in #1090 and #1094
=> Convert RemoveROOversamplingGadget->ChannelGadget

toolboxes/mri_image/hoMRImage.h
These changes allow compilation of approximately 25 more targets when building on macOS with Clang.
=> Clang-compatible extension of Gadgetron::Core::IO namespace

azure-pipelines.yml
The correct environment variable is 'isCI' not 'IS_CI', as defined at the top of the file - oops.
=> Publish conda package on CI builds

azure-pipelines.yml, test/integration/get_data.py
Because the package publish is a job it was provided the default of 60 minutes.
However the test/package stages can exceed that period - meaning the
package job would exceed the default timeout and fail before it had an
opportunity to execute.
=> Provide a job timeout for the package publish job

azure-pipelines.yml, test/integration/get_data.py
This change adds -y to the conda create command, which was timing out on successful CI builds waiting on input from stdin to accept new package revisions. 
Also fixed a typo made when adding the unhanded timeout exception.
=> Accept package revisions when building package publish environment

Dockerfile
As part of improving the packaging of Gadgetron docker images, we should add the repo label that Github expects for organization-owned Docker images per instructions here: https://docs.github.com/en/packages/learn-github-packages/connecting-a-repository-to-a-package#connecting-a-repository-to-a-container-image-using-the-command-line. This should tie our docker images into the Package list within the repository's main page. 
There are likely other annotation key Labels we should use too (for versioning etc) per: https://github.com/opencontainers/image-spec/blob/main/annotations.md#pre-defined-annotation-keys, but I want to start with seeing if this label behaves as expected.
=> Add label tying Docker builds to repository

conda/package.sh, environment.yml, test/CMakeLists.txt
This PR removes the CEFCA channel from Gadgetron (newer version of plplot is available from conda-forge).  It also cleans up the conda environment specification, and finally - improves testing behavior when using GTest on macOS.
=> Build pipeline cleanup

gadgets/dicom/dicom_ismrmrd_utility.cpp, toolboxes/mri_core/mri_core_utility.cpp, toolboxes/mri_core/mri_core_utility.h
With recent changes pushed to ISMRMRD and Gadgetron, some minor inconsistencies were introduced that were not caught by the default compilation stream, but show up when building with Clang and LLVM.
The changes to ISMRMRD::UserParameterLong type tracks changes introduced to ISMRMRD [here](https://github.com/ismrmrd/ismrmrd/commit/838840dd17a1267304785b09783646d3d19ee678#diff-0499892cd7c35d5b912bdb67890e8f0c2addd905def1a312cd67585d54e33864L345).
=> Minor code consistency improvements

apps/gadgetron/StreamConsumer.h
To resolve issue #1204, this PR removes an unused path variable within StreamConsumer.
=> Removed unused path variable

.devcontainer/devcontainer.json
This PR updates the devcontainer specification to the new json file structure to be compatible with recent versions of VScode. 
Per the devcontainer.json specification (https://containers.dev/implementors/json_reference/), all VScode customizations must be isolated to a specific "customizations" parent (https://containers.dev/supporting). 
We will likely need to modify this again to support codespaces or similar, but this should allow local VScode development containers to work with devcontainer extension versions newer than v0.275.1
=> Update devcontainer.json to new spec

gadgets/mri_core/IsmrmrdDumpGadget.cpp, gadgets/mri_core/IsmrmrdDumpGadget.h
add file lock to ismrmrd dump gadget
use case is multiple scans can write into the same noise dump file; in rare case, it can become a racing condition.
=> add file lock for dump gadget

gadgets/dicom/DicomFinishGadget.h, gadgets/dicom/DicomImageWriter.cpp, gadgets/dicom/dicom_ismrmrd_utility.h
DCMTK 3.6.7 made INCLUDE_CSTDIO etc errors. So
just use the C++ files directly.
Fixes #1277
=> no longer use obsolete DCMTK macros
