- gadgets/mri_core/NoiseAdjustGadget.cpp
- gadgets/mri_core/NoiseAdjustGadget.h
(saved variable was static instead of member variable).
> Fixed bug in NoiseAdjustGadged 

- CMakeLists.txt
- gadgets/gtPlus/GtPlusGadgetOpenMP.cpp
- toolboxes/core/GadgetronCommon.h
- toolboxes/core/cpu/hoMatrix.hxx
- toolboxes/core/cpu/hoNDArray_utils.h
- toolboxes/gtplus/algorithm/gtPlusGRAPPA.h
- toolboxes/gtplus/algorithm/gtPlusOperator.h
- toolboxes/gtplus/algorithm/gtPlusSPIRIT.h
- toolboxes/gtplus/algorithm/gtPlusSPIRIT2DTOperator.h
- toolboxes/gtplus/algorithm/gtPlusSPIRITNoNullSpace2DTOperator.h
- toolboxes/gtplus/algorithm/gtPlusWavelet3DOperator.h
- toolboxes/gtplus/algorithm/gtPlusWaveletOperator.h
- toolboxes/gtplus/workflow/gtPlusISMRMRDReconUtil.cpp
- toolboxes/gtplus/workflow/gtPlusISMRMRDReconUtil.hxx
- toolboxes/gtplus/workflow/gtPlusISMRMRDReconWorker2DT.h
- toolboxes/gtplus/workflow/gtPlusISMRMRDReconWorker2DTSPIRIT.h
- toolboxes/gtplus/workflow/gtPlusISMRMRDReconWorker3DT.h
- toolboxes/gtplus/workflow/gtPlusISMRMRDReconWorker3DTSPIRIT.h
remove GCC_OLD_FLAG.
add checks for minimal compiler versions.
> Remove gcc old flag

- CMakeLists.txt
- toolboxes/core/cpu/CMakeLists.txt
- toolboxes/core/cpu/cpucore_export.h
- toolboxes/core/cpu/math/CMakeLists.txt
- toolboxes/core/cpu/math/cpucore_math_export.h
- toolboxes/core/cpu/math/hoNDArray_elemwise.cpp
- toolboxes/fft/cpu/CMakeLists.txt
- toolboxes/fft/cpu/cpufft_export.h
- toolboxes/gtplus/CMakeLists.txt
- toolboxes/gtplus/GtPlusExport.h
- toolboxes/gtplus/GtPlusIOExport.h
- toolboxes/gtplus/workflow/gtPlusISMRMRDReconWorker2DT.h
- toolboxes/gtplus/workflow/gtPlusISMRMRDReconWorker3DT.h
- toolboxes/linalg/CMakeLists.txt
- toolboxes/linalg/linalg_export.h
- toolboxes/mri/epi/CMakeLists.txt
- toolboxes/mri/epi/EPIExport.h
- toolboxes/registration/optical_flow/cpu/CMakeLists.txt
- toolboxes/registration/optical_flow/cpu/cpureg_export.h
> remove static linking

- gadgets/gtPlus/config/GT_2DT_Cartesian.xml
- gadgets/gtPlus/config/GT_2DT_Cartesian_Dicom.xml
- gadgets/gtPlus/config/GT_2DT_Cartesian_DualLayer_Gateway_L1SPIRIT.xml
- gadgets/gtPlus/config/GT_2DT_Cartesian_DualLayer_Gateway_SPIRIT.xml
- gadgets/gtPlus/config/GT_2DT_Cartesian_GFactor.xml
- gadgets/gtPlus/config/GT_2DT_Cartesian_ImageTrigger_Dicom.xml
- gadgets/gtPlus/config/GT_2DT_Cartesian_L1SPIRIT.xml
- gadgets/gtPlus/config/GT_2DT_Cartesian_PseudoReplica_SNRUnitRecon.xml
- gadgets/gtPlus/config/GT_2DT_Cartesian_SPIRIT.xml
- gadgets/gtPlus/config/GT_2DT_FatWater.xml
- gadgets/gtPlus/config/GT_2DT_HASTE.xml
- gadgets/gtPlus/config/GT_2DT_HASTE_MOCO_AVE.xml
- gadgets/gtPlus/config/GT_2DT_LGE.xml
- gadgets/gtPlus/config/GT_2DT_MOLLI.xml
- gadgets/gtPlus/config/GT_2DT_MOLLI_Offline.xml
- gadgets/gtPlus/config/GT_2DT_Perfusion.xml
- gadgets/gtPlus/config/GT_2DT_RTCine_L1SPIRIT_PhysioInterp.xml
- gadgets/gtPlus/config/GT_2DT_RTCine_L1SPIRIT_PhysioInterp_DualLayer_Gateway.xml
- gadgets/gtPlus/config/GT_2DT_RealTimeCine.xml
- gadgets/gtPlus/config/GT_2DT_RealTimeFlow.xml
- gadgets/gtPlus/config/GT_2DT_T2W.xml
- gadgets/gtPlus/config/GT_3DT_Cartesian.xml
- gadgets/gtPlus/config/GT_3DT_Cartesian_GFactor.xml
- gadgets/gtPlus/config/GT_3DT_Cartesian_L1SPIRIT.xml
- gadgets/gtPlus/config/GT_3DT_Cartesian_SingleLayer_L1SPIRIT.xml
- gadgets/mri_core/RemoveROOversamplingGadget.cpp
- gadgets/mri_core/RemoveROOversamplingGadget.h
- gadgets/mri_core/default.xml
- gadgets/mri_core/default_optimized.xml
- gadgets/mri_core/default_short.xml
Fix issue "RemoveROOverSampling bug".
> Consolidate remove over sampling

- chroot/mount_image.sh
- chroot/start-gadgetron-from-image.sh
a) Enhance the mount_image.sh to check not only the mount point but the existence of folder content
b) Let the script to start gadgetron from the image, as its name indicates.
> update two chroot related scripts

- toolboxes/core/cpu/hostutils/FileInfo.h
a small fix for vs2013 compilation
> a small fix for vs2013 compilation

- toolboxes/registration/optical_flow/cpu/solver/hoImageRegDeformationFieldBidirectionalSolver.h
- toolboxes/registration/optical_flow/cpu/transformation/hoImageRegDeformationField.h
Improve the reg performance by fixing a bug and increasing the number of iterations.
> fix a few bugs in reg toolbox

- .gitmodules
- apps/clients/CMakeLists.txt
- apps/clients/gadgetron_ismrmrd_client/CMakeLists.txt
- apps/clients/gadgetron_ismrmrd_client/gadgetron_ismrmrd_client.cpp
Reverts gadgetron/gadgetron#90
> Revert "Move client"

- gadgets/python/gadgetron.py
- gadgets/python/pure_python_demo.py
This pull request fixes a bug in gadgetron.py and provides a working example of running a pure Python chain.
> Added example script for running a pure python Gadget chain

- apps/gadgetron/Gadget.h
- apps/gadgetron/GadgetStreamController.cpp
- apps/gadgetron/GadgetStreamController.h
- apps/gadgetron/GadgetStreamInterface.h
- gadgets/moco/RegistrationAveragingGadget.h
- gadgets/moco/RegistrationScatteringGadget.h
- gadgets/mri_core/AcquisitionFinishGadget.cpp
- gadgets/mri_core/AcquisitionFinishGadget.h
- gadgets/mri_core/NoiseAdjustGadget.cpp
- gadgets/python/CMakeLists.txt
- gadgets/python/GadgetInstrumentationStreamController.cpp
- gadgets/python/GadgetInstrumentationStreamController.h
- gadgets/python/GadgetronPythonMRI.cpp
- gadgets/python/gadgetron.py
- gadgets/python/mixed_gadgets.py
- gadgets/python/remove_2x_oversampling.py
@inati , @naegelejd , @dchansen 
This is it!
We can now use the Python Gadgets directly in Python but ALSO the CPP Gadgets directly in Python using a Python WrapperGadget.
Please see the mixed_gadgets.py for an example of how this works.
> Python instrumentation

- apps/gadgetron/CMakeLists.txt
Need to install GadgetStreamInterface.h to enable the compilation of external library depending gadgetron.
> need to install GadgetStreamInterface.h

- chroot/gadgetron_chroot.conf
- chroot/install_chroot_image.sh
- chroot/mount_image.sh
- chroot/run-webapp.sh.in
Update scripts for the new chroot script path.
> update for the new chroot script path

- gadgets/gtPlus/GtPlusRecon2DTGadget.cpp
- gadgets/gtPlus/GtPlusRecon3DTGadget.cpp
- toolboxes/gtplus/workflow/gtPlusISMRMRDReconWorkOrder.h
- toolboxes/gtplus/workflow/gtPlusISMRMRDReconWorker2DT.h
- toolboxes/gtplus/workflow/gtPlusISMRMRDReconWorker3DT.h
make a few changes to allow noacceleration data to go through recon chain.
add a parameter to workorder to allow future grappa initialization for spirit recon.
> Gtplus noacceleration

- gadgets/grappa/GrappaWeightsCalculator.cpp
The posv problem in rtgrappa is fixed for the newly added cpu version.
> fix the posv problem in cpu rtgrappa

- gadgets/gtPlus/GtPlusReconGadget.cpp
- gadgets/gtPlus/config/GT_3DT_Cartesian.xml
- toolboxes/gtplus/algorithm/gtPlusGRAPPA.h
- toolboxes/gtplus/workflow/gtPlusISMRMRDReconWorker2DT.h
- toolboxes/mri_core/mri_core_grappa.cpp
Fix a few bugs in gtplus.
Properly support one direction acceleration in 3D recon.
Souheil's 3D data now can be reconed correctly.
> Gtplus bug fix

- toolboxes/core/cpu/image/hoNDImageContainer2D.h
- toolboxes/gtplus/algorithm/gtPlusOperator.h
fix really small issues in the code.
> fix a few small const issues and real() calls

- toolboxes/cloudbus/CloudBus.cpp
Fixes issue: https://github.com/gadgetron/gadgetron/issues/115
> Removed ACE_OS namespace from if_nameindex function calls

- toolboxes/mri_core/mri_core_def.h
add definitions for per flow mapping
> add flow map definitions

- toolboxes/registration/optical_flow/cpu/application/hoImageRegContainer2DRegistration.h
allow reg driver function to use initialized motion field
> allow reg driver function to set initial motion field

- gadgets/gtPlus/GtPlusReconGadget.cpp
Fix the text based cloud setup
> fix the text based cloud

- apps/clients/gadgetron_ismrmrd_client/gadgetron_ismrmrd_client.cpp
- gadgets/dicom/DicomFinishGadget.cpp
fix the dicom finish gadget and fix the client for blob writer
> fix the dicom finish gadget and client

- gadgets/mri_core/PhysioInterpolationGadget.cpp
- gadgets/mri_core/PhysioInterpolationGadget.h
Attach RR in ms to the physio interp output series.
> physio interp has RR in its image comment and sequence description

- toolboxes/mri_core/mri_core_def.h
Add R2Star data role definition
> add data role R2Star

- gadgets/dicom/DicomFinishGadget.cpp
Update the gadgetron for the changing of ismrmrd sequence parameter section.
> Add sequence type

- gadgets/epi/epi_gtplus_grappa.xml
remove the unused gadget properties for epi grappa xml.
> fix the grappa epi xml

- gadgets/gtPlus/config/GT_3DT_Cartesian.xml
- toolboxes/gtplus/workflow/gtPlusISMRMRDReconWorkFlowCartesian.h
- toolboxes/gtplus/workflow/gtPlusISMRMRDReconWorker3DT.h
- toolboxes/gtplus/workflow/gtPlusISMRMRDReconWorker3DTGRAPPA.h
Tight up the memory usage for 3DT recon.
Speed up slow steps by inline computation.
> Improve mem 3 dt

- toolboxes/core/gpu/cuNDArray_elemwise.cu
- toolboxes/core/gpu/cuSparseMatrix.cu
> Modifications for Mac OsX compilation

- toolboxes/mri_core/mri_core_def.h
add two data role definition for perfusion Gd concentration.
> add data role definition for perf and aif Gd concentration

- gadgets/gtPlus/GtPlusGadgetImageArray.cpp
- toolboxes/gtplus/workflow/gtPlusISMRMRDReconWorker3DT.h
- toolboxes/gtplus/workflow/gtPlusISMRMRDReconWorker3DTGRAPPA.h
- toolboxes/mri_core/mri_core_def.h
- toolboxes/mri_core/mri_core_grappa.cpp
- toolboxes/mri_core/mri_core_grappa.h
a) Add functions for 3D grappa.
b) Replace the old 3D grappa with new functions.
c) Optimize peak memory usage for 3D recon.
> 3 d mri core

- toolboxes/gtplus/workflow/gtPlusISMRMRDReconWorkFlowCartesian.h
- toolboxes/gtplus/workflow/gtPlusISMRMRDReconWorkFlowCartesian3DT.h
- toolboxes/mri_core/mri_core_grappa.h
Add a few fixes for the 3D Gfactor map organization.
> fix the 3D grappa gfactor computation

- gadgets/matlab/MatlabBufferGadget.cpp
- gadgets/matlab/bufferRecon.m
- test/integration/cases/matlab.cfg
Reference data was not being sent properly.
> Fixed bug in matlab buffer conversion.

- gadgets/gtPlus/GtPlusAccumulatorWorkOrderTriggerGadget.cpp
- gadgets/gtPlus/GtPlusReconGadget.cpp
- gadgets/gtPlus/GtPlusReconJob2DTGadgetCloud.cpp
- toolboxes/fft/cpu/hoNDFFT.cpp
- toolboxes/gtplus/workflow/gtPlusISMRMRDReconUtil.hxx
- toolboxes/gtplus/workflow/gtPlusISMRMRDReconWorker2DT.h
- toolboxes/gtplus/workflow/gtPlusISMRMRDReconWorker3DT.h
@xueh2, please check this thoroughly.
> Cleaned up warnings when compiling with clang on macos

- gadgets/mri_core/SimpleReconGadget.cpp
@naegelejd , @inati , @xueh2 
This needs urgent merging. There is a massive leak in SimpleReconGadget, in fact it leaks ALL the data coming into it.
> Fixed memory leak in SimpleReconGadget

- apps/gadgetron/gadgetron_xml.cpp
This is a fix for
https://github.com/gadgetron/gadgetron/issues/185
> Config parse fix

- toolboxes/cloudbus/cloudbus_relay.cpp
This enables the user to specify the port of the cloudbus relay as a command line argument.
> Added functionality to specify cloudbus port on startup

- apps/gadgetron/webapp/gadgetron_web_app.cfg
- apps/gadgetron/webapp/gadgetron_web_app.py
This causes the old log file to be backed up by the web app before starting a new one. It is important to be able to retrieve the old log in the event of a crash.
> Old log file is backed up in web app

- gadgets/grappa/config/grappa.xml
- gadgets/grappa/config/grappa_float.xml
- gadgets/grappa/config/grappa_float_cpu.xml
- gadgets/interventional_mri/grappa_device.xml
These RT grappa configs need support for asymmetric echo.
> Added asymmetric echo adjust to rt grappa configurations

- test/integration/run_gadgetron_test.py
> fixing run_gadgetron_test.py to include Matlab paths

- apps/gadgetron/main.cpp
- apps/gadgetron/webapp/gadgetron_web_app.cfg
- apps/gadgetron/webapp/gadgetron_web_app.in
- apps/gadgetron/webapp/gadgetron_web_app.py
Changes:
* Small fixes to make the web app more robust when MKL is used. 
* Also removed some CULA paths no longer used. 
* The web app now starts the cloudbus relay
* The web app can take configuration parameters from cfg file to connect to cloudbus relay
* gadgetron main app now has command line arguments reflecting all the parameters that are in the gadgetron.xml file to allow them to be overwritten on the command line.
> Added some missing paths in webapp

- gadgets/mri_core/PseudoReplicatorGadget.h
- test/integration/cases/pseudoreplica.cfg
Fix the test
In windows, it is found to give slightly different results than linux run. I am supposing for pseudoreplicate test, comparing scaling is sufficient?
> Pseudo replicator gadget export

- toolboxes/klt/cpu/hoNDKLT.cpp
Bug fix
This bug will causes the numOfKeptChannels > numofAcquiredChannels
> fix a bug in hoNDKLT

- toolboxes/gtplus/workflow/gtPlusISMRMRDReconUtil.hxx
- toolboxes/mri_core/mri_core_coil_map_estimation.cpp
- toolboxes/mri_core/mri_core_coil_map_estimation.h
to support cleaner code in generic chain
> adjust coil map estimation functions for generic chain

- toolboxes/klt/cpu/hoNDKLT.cpp
- toolboxes/klt/cpu/hoNDKLT.h
fix for uncombined channels
remove some duplicates
> Bug fix klt

- gadgets/grappa/GrappaWeightsCalculator.cpp
- gadgets/interventional_mri/grappa_device.xml
Fix the cpu part of irt grappa recon with uncombined channels
Simplify the code for accelerated and non-accelerated cases
> Fix cpu irt grappa

- gadgets/python/PythonGadget.h
This include file is needed for windows debug compilation of python gadget.
> fix the windows debug compilation

- test/integration/run_all_tests.py
- test/integration/run_gadgetron_test.py
This PR adds some more sane parameter handling to the integration tests scripts and enables test of a running instance. 
Let me know what you think. Please don't merge yet because I have to update the buildbot master to match before merging. But let me know if you are OK with it.
> Integration test

- gadgets/CMakeLists.txt
> fix the python info finding

- gadgets/mri_core/CMakeLists.txt
- gadgets/mri_core/GenericReconKSpaceFilteringGadget.cpp
- gadgets/mri_core/GenericReconKSpaceFilteringGadget.h
- gadgets/mri_core/Generic_Cartesian_Grappa_RealTimeCine.xml
- gadgets/mri_core/Generic_Cartesian_Grappa_T2W.xml
add kspace filter gadget for the generic chain
> add kspace filter gadget

- test/integration/CMakeLists.txt
For the cases 'a' is real and the hoNDArrays complex.
These were implemented for cuNDArrays, but not for hoNDArrays.
> Add some axpy cases to hoNDArray

- docker/cuda_331_openblas/Dockerfile
- docker/no_cuda_openblas/Dockerfile
install plplot to enable figure creation
> add installation of plplot

- gadgets/hyper/gpuCSICoilEstimationGadget.cpp
- gadgets/matlab/MatlabUtils.cpp
- gadgets/mri_core/BucketToBufferGadget.cpp
- gadgets/pmri/gpuBufferSensePrepGadget.cpp
- toolboxes/mri_core/mri_core_data.h
Another addition of boost::optional
> Changed IsmrmrdDataBuffered to make trajectory explicitly optional

- gadgets/mri_core/CMakeLists.txt
- gadgets/mri_core/GenericCartesianGrappaReconGadget.cpp
- gadgets/mri_core/GenericCartesianGrappaReconGadget.h
- gadgets/mri_core/GenericCartesianReconReferencePrepGadget.cpp
- gadgets/mri_core/GenericReconPartialFourierHandlingGadget.cpp
- gadgets/mri_core/Generic_Cartesian_Grappa.xml
Fix for noacceleration mode in generic chain
Add a Generic_Cartesian_Grappa.xml for general recon cases
> fix the generic chain for noacceleration

- gadgets/mri_core/BucketToBufferGadget.cpp
- gadgets/mri_core/NoiseAdjustGadget.cpp
-An end-of-line missing in one GDEBUG instance in NoiseAdjustGadget.cpp
-Typo: replaced one instance of "N_dimension" with "S_dimension" in process_config in BucketToBufferGadget.cpp
> Fixed two minor bugs.

- gadgets/grappa/config/CMakeLists.txt
- gadgets/grappa/config/grappa_cpu.xml
- gadgets/interventional_mri/CMakeLists.txt
- gadgets/interventional_mri/grappa_device_cpu.xml
@xueh2 can you check and merge before making new image.
> Added more grappa configurations for interventional MRI without GPU

- chroot/mount_image.sh.in
- chroot/start-gadgetron-from-image.sh.in
- chroot/start-gadgetron.sh.in
- chroot/start.sh.in
- chroot/umount_image.sh
Allow gadgetron is started in chroot with a log file
Improve robustness for checking mount and umount status
> add parameter to allow chroot gadgetron to pipe out log file

- gadgets/python/gadgets/CMakeLists.txt
- gadgets/python/gadgets/IDEAL.py
- gadgets/python/gadgets/accumulate_and_recon.py
- gadgets/python/gadgets/bucket_recon.py
- gadgets/python/gadgets/gadgetron.py
- gadgets/python/gadgets/remove_2x_oversampling.py
- gadgets/python/gadgets/rms_coil_combine.py
- toolboxes/python/python_IsmrmrdReconData_converter.h
- toolboxes/python/python_hoNDArray_converter.h
- toolboxes/python/python_numpy_wrappers.h
- toolboxes/python/python_toolbox.cpp
, and fixed a bug where returning  a non C-style array would not work
> Changed to Numpy to use Fortran order

- chroot/gadgetron-dependency-query.sh.in
- chroot/gadgetron_ismrmrd_client.sh.in
- chroot/run-gadgetron-dependency-query.sh.in
- chroot/run-gadgetron_ismrmrd_client.sh.in
Update dependency query and client scripts to use time out format.
> use time out client

- gadgets/python/gadgets/CMakeLists.txt
- gadgets/python/gadgets/IDEAL.py
- gadgets/python/gadgets/accumulate_and_recon.py
- gadgets/python/gadgets/bucket_recon.py
- gadgets/python/gadgets/gadgetron.py
- gadgets/python/gadgets/remove_2x_oversampling.py
- gadgets/python/gadgets/rms_coil_combine.py
- toolboxes/python/python_IsmrmrdReconData_converter.h
- toolboxes/python/python_hoNDArray_converter.h
- toolboxes/python/python_numpy_wrappers.h
- toolboxes/python/python_toolbox.cpp
Fixed a bug in the previous commit, caused by someone not running the right integration test.
> Python fortran order

- toolboxes/cloudbus/CMakeLists.txt
- toolboxes/cloudbus/cloudbus_io.cpp
- toolboxes/cloudbus/cloudbus_io.h
Add export/import for cloudbus_io functions.
> add export for cloudbus_io

- toolboxes/cloudbus/cloudbus_io.h
> fix the compiling errors

- toolboxes/core/cpu/math/hoNDArray_reductions.cpp
Removed some unused variables in dotc and dotu in hoNDArray_reductions.cpp
(Do I get extra points for a pull request that just removes lines of code? ;-)
> Removed unused variables in hoNDArray_reductions.cpp

- gadgets/gtPlus/CMakeLists.txt
- toolboxes/gtplus/solver/gtPlusLSQRSolver.h
- toolboxes/gtplus/workflow/gtPlusISMRMRDReconWorker2DTSPIRIT.h
- toolboxes/gtplus/workflow/gtPlusISMRMRDReconWorker3DTSPIRIT.h
- toolboxes/operators/CMakeLists.txt
- toolboxes/operators/cpu/CMakeLists.txt
- toolboxes/operators/cpu/cpuOperatorExport.h
- toolboxes/operators/cpu/hoSPIRIT2DOperator.cpp
- toolboxes/operators/cpu/hoSPIRIT2DOperator.h
- toolboxes/operators/cpu/hoSPIRIT2DTOperator.cpp
- toolboxes/operators/cpu/hoSPIRIT2DTOperator.h
- toolboxes/operators/cpu/hoSPIRIT3DOperator.cpp
- toolboxes/operators/cpu/hoSPIRIT3DOperator.h
- toolboxes/operators/cpu/hoSPIRITOperator.cpp
- toolboxes/operators/cpu/hoSPIRITOperator.h
- toolboxes/operators/linearOperator.h
add spirit operators into toolbox cpuoperator
add library gadgetron_toolbox_cpuoperator
> Spirit operators

- toolboxes/fft/cpu/CMakeLists.txt
- toolboxes/plplot/ut/CMakeLists.txt
Fix windows compilation error
Fix ut install path for gadgetron_ut_plplot
> fix windows compilation; fix the install path for a ut case

- toolboxes/fft/cpu/hoNDFFT.cpp
- toolboxes/fft/cpu/hoNDFFT.h
This replaces the boost::mutex with std::mutex in hoNDFFT
> Replaced boost mutex with std::mutex in hoNDFFT

- toolboxes/core/cpu/math/hoNDArray_elemwise.cpp
Add more functions in hoNDArray_elemwise.cpp
> More functions ho nd array elemwise

- toolboxes/cloudbus/shut_down_idle_nodes.py
script now predicts desired number of nodes and ALWAYS writes file.
> Modified node shutdown

- chroot/gadgetron_chroot.conf
- chroot/install_chroot_image.sh
- chroot/mount.sh
- chroot/start-webapp.sh.in
- chroot/stop.sh
- gadgets/mri_core/CMakeLists.txt
- gadgets/mri_core/default_measurement_dependencies_ismrmrd_storage.xml
Add changes to support the ismrmrd storage
a) a xml is added to store dependencies
b) the chroot installation scripts are improved to make sure properly umounting old folders
c) the stored ismrmrd data is at ${chroot_gadgetron_dir}/tmp/gadgetron_data
> add changes to support ismrmrd storage

- docker/base/ubuntu_1404/Dockerfile
- docker/base/ubuntu_1404_cuda75/Dockerfile
- docker/incremental/ubuntu_1404_buildslave/Dockerfile
- docker/incremental/ubuntu_1404_cuda/Dockerfile
- docker/incremental/ubuntu_1404_no_cuda/Dockerfile
Here are some Dockerfiles for a basic Ubuntu setup with proper OpenBLAS and Python support.
> Docker structure

- chroot/CMakeLists.txt
- chroot/clean_gadgetron_data.sh
- chroot/install_chroot_image.sh
Add scripts to clean the stored data
> install clean_gadgetron_data.sh to /tmp/gadgetron_data

- chroot/clean_gadgetron_data.sh
- chroot/install_chroot_image.sh
Add changes to allow specifying the folder to store saved ismrmrd data
> add changes to allow change the ismrmrd data folder

- chroot/clean_gadgetron_data.sh
when checking the disk usage, should check /tmp/gadgetron_data point
> fix bugs when detecting disk usage in clean_gadgetron_data.sh

- apps/gadgetron/webapp/gadgetron_web_app.py
Update two calls for new psutil
Make sure docker cmake is always building the release version
> update web app script for new psutil

- chroot/install_chroot_image.sh
Update chroot install script for docker images
> update chroot install script for docker based solution

- docker/tag_image_with_version.sh
add optional gtprep tag into the script
> add optional gtprep sha1 for tag docker images

- toolboxes/core/cpu/math/hoNDArray_elemwise.cpp
- toolboxes/core/cpu/math/hoNDArray_linalg.h
When compiling with Intel compilers there are lots of complaints which this pull request should be able to address.
> Fixed some complaints when compiling with Intel compilers.

- gadgets/mri_core/CMakeLists.txt
- gadgets/mri_core/GenericCartesianReconReferencePrepGadget.cpp
- gadgets/mri_core/GenericReconEigenChannelGadget.cpp
- gadgets/mri_core/GenericReconEigenChannelGadget.h
- gadgets/mri_core/Generic_Cartesian_Grappa_T2W.xml
- toolboxes/mri_core/CMakeLists.txt
- toolboxes/mri_core/mri_core_utility.cpp
- toolboxes/mri_core/mri_core_utility.h
Add eigen channel gadget working on recon data
> add eigen channel gadget in the generic chain

- gadgets/dicom/CMakeLists.txt
- gadgets/interventional_mri/CMakeLists.txt
- gadgets/mri_core/CMakeLists.txt
- gadgets/mri_core/GenericCartesianGrappaReconGadget.cpp
- gadgets/mri_core/GenericCartesianGrappaReconGadget.h
- gadgets/mri_core/GenericReconCartesianGrappaGadget.cpp
- gadgets/mri_core/GenericReconCartesianGrappaGadget.h
- gadgets/mri_core/GenericReconCartesianReferencePrepGadget.cpp
- gadgets/mri_core/GenericReconCartesianReferencePrepGadget.h
- gadgets/mri_core/GenericReconEigenChannelGadget.cpp
- gadgets/mri_core/GenericReconGadget.cpp
- gadgets/mri_core/GenericReconGadget.h
- gadgets/mri_core/GenericReconImageArrayScalingGadget.h
- gadgets/mri_core/Generic_Cartesian_Grappa.xml
- gadgets/mri_core/Generic_Cartesian_Grappa_EPI.xml
- gadgets/mri_core/Generic_Cartesian_Grappa_RealTimeCine.xml
- gadgets/mri_core/Generic_Cartesian_Grappa_T2W.xml
- toolboxes/mri_core/CMakeLists.txt
a) Add GenericReconGadget as a potential base class for specific recon
b) Rename GenericCartesianGrappaReconGadget to GenericReconCartesianGrappaGadget, so all generic recon chains have names starting with GenericRecon ...
> Add generic recon base gadget

- gadgets/epi/EPIReconXGadget.cpp
fix EPI recon X if trajectory is recomputed
> fix EPI recon x for recomputing trajectory

- apps/gadgetron/gadgetron.xml.example
- apps/gadgetron/gadgetron_xml.cpp
- apps/gadgetron/gadgetron_xml.h
- apps/gadgetron/main.cpp
- apps/gadgetron/webapp/gadgetron_web_app.cfg
- apps/gadgetron/webapp/gadgetron_web_app.in
- apps/gadgetron/webapp/gadgetron_web_app.py
- docker/incremental/ubuntu_1404_cuda55/Dockerfile
- docker/incremental/ubuntu_1404_cuda75/Dockerfile
- docker/incremental/ubuntu_1404_no_cuda/Dockerfile
- toolboxes/cloudbus/CloudBus.cpp
- toolboxes/cloudbus/CloudBus.h
This allows easy integration with an external load balancer instead of the relay. Relay is still supported
> Allow specification of a single (load balanced) endpoint CB

- gadgets/gtPlus/GtPlusAccumulatorWorkOrderTriggerGadget.cpp
- gadgets/gtPlus/GtPlusReconGadget.cpp
- gadgets/mri_core/GenericReconCartesianGrappaGadget.cpp
- gadgets/mri_core/GenericReconCartesianGrappaGadget.h
- gadgets/mri_core/GenericReconKSpaceFilteringGadget.cpp
- toolboxes/gtplus/workflow/gtPlusISMRMRDReconWorker2DT.h
Fix downstream coil compression without acceleration
Make sure kspace filter center aligned with encoded matrix
Fix a bug in gtplus for embedded ref filling
> Fix down stream coil compression no acceleration kspace filter2

- gadgets/mri_core/CMakeLists.txt
- gadgets/mri_core/GenericReconCartesianGrappaGadget.cpp
- gadgets/mri_core/GenericReconCartesianReferencePrepGadget.cpp
- gadgets/mri_core/GenericReconCartesianReferencePrepGadget.h
- gadgets/mri_core/Generic_Cartesian_Grappa.xml
- gadgets/mri_core/Generic_Cartesian_Grappa_EPI.xml
- gadgets/mri_core/Generic_Cartesian_Grappa_FatWater.xml
- gadgets/mri_core/Generic_Cartesian_Grappa_RealTimeCine.xml
- gadgets/mri_core/Generic_Cartesian_Grappa_SNR.xml
- gadgets/mri_core/Generic_Cartesian_Grappa_T2W.xml
add fat water xml in generic chain
extend prepare_ref_always in ref prep step to all calib modes
> Add fatwater xml 2

- gadgets/distributed/DistributeGadget.cpp
- toolboxes/cloudbus/CloudBus.cpp
- toolboxes/cloudbus/CloudBus.h
This fixes the problem with the distributed cases.
> Fix for crashes in distributed test cases

- gadgets/mri_core/GenericReconImageArrayScalingGadget.cpp
- gadgets/mri_core/GenericReconImageArrayScalingGadget.h
Added some comments to the GenericReconImageArrayScalingGadget.
Michael, since no new code is added, maybe you just want to wait for the next "real" pull request and add them at that time.
Hui,
Is there a reason for using "maxAbsolute", since you have already taken the magnitude of the image?
> Comments for GenericReconImageArrayScalingGadget

- gadgets/mri_core/BucketToBufferGadget.cpp
- gadgets/mri_core/BucketToBufferGadget.h
- gadgets/mri_core/Generic_Cartesian_Grappa.xml
- gadgets/mri_core/Generic_Cartesian_Grappa_RealTimeCine.xml
- gadgets/mri_core/Generic_Cartesian_Grappa_SNR.xml
- gadgets/mri_core/Generic_Cartesian_Grappa_T2W.xml
fix the bug in BucketToBufferGadget, found in the multiple slice SNR dataset
Add verbose to this gadget for better debug
Adjust Generic SNR xml to trigger at the end of the scan
> fix the bug found in BuecketToBufferGadget; add verbose control

- gadgets/mri_core/Generic_Cartesian_Grappa_FatWater.xml
> Fixed dimensions in FW

- toolboxes/mri_core/mri_core_spirit.cpp
- toolboxes/mri_core/mri_core_spirit.h
Add functions to compute kspace-image domain kernel for spirit 3d
> add functions to computer kspace-image domain kernel for 3d spirit

- toolboxes/fatwater/fatwater.cpp
> small fixes for windows compilation

- toolboxes/CMakeLists.txt
- toolboxes/ffd/BSplineFFD.h
- toolboxes/ffd/BSplineFFD2D.h
- toolboxes/ffd/BSplineFFD3D.h
- toolboxes/ffd/BSplineFFD4D.h
- toolboxes/ffd/CMakeLists.txt
- toolboxes/ffd/FFDBase.h
- toolboxes/ffd/MLFFD.h
- toolboxes/gtplus/CMakeLists.txt
move ffd out of gtplus, as a start to remove toolbox/gtplus
> Move ffd out of gtplus

- toolboxes/mri/epi/EPIReconXObjectTrapezoid.h
Added off-center correction for trapezoidal EPI readout.
> Added off-center correction for EPI

- toolboxes/plplot/GtPLplot.cpp
fix CoilQA plot, starting of coil string from 1
> fix noise qa plot; coil string starts from 1 now

- docker/base/ubuntu_1404/Dockerfile
> docker base install dcmtk

- toolboxes/cmr/CMakeLists.txt
- toolboxes/cmr/cmr_kspace_binning.cpp
- toolboxes/cmr/cmr_kspace_binning.h
- toolboxes/cmr/cmr_motion_correction.cpp
- toolboxes/cmr/cmr_motion_correction.h
- toolboxes/cmr/cmr_time_stamp.cpp
- toolboxes/cmr/cmr_time_stamp.h
- toolboxes/registration/optical_flow/cpu/transformation/hoImageRegHomogenousTransformation.h
Second PR for binning and cmr toolbox
a) add cmr_time_stamp.h/.cpp
b) add cmr_motion_correction.h/.cpp
c) add time stamp processing and respiratory navigator estimation to binning
> Add cardiac time stamp processing respiratory navigator

- gadgets/mri_core/BucketToBufferGadget.cpp
- gadgets/mri_core/GenericReconGadget.cpp
fix two problems found by testing ismrmrd create test data
> fix two problems found by testing ismrmrd create test data script

- gadgets/mri_core/GenericReconCartesianGrappaGadget.cpp
turn off outer loop openmp for 3D recon
> turn off outer loop openmp for 3D recon

- toolboxes/mri_core/mri_core_def.h
> add perf permeability map data role

- gadgets/compression/CMakeLists.txt
- gadgets/compression/config/CMR_2DT_RTCine_KspaceBinning_Cloud_Compression.xml
@xueh2 please merge if you are OK with this.
> Added compression version of cloud based binning

- cmake/FindMKL.cmake
> Improve find mkl

- gadgets/cmr/config/BinningCine/CMR_2DT_RTCine_KspaceBinning.xml
- gadgets/cmr/config/BinningCine/CMR_2DT_RTCine_KspaceBinning_Cloud.xml
- gadgets/compression/config/CMR_2DT_RTCine_KspaceBinning_Cloud_Compression.xml
turn off sending raw images in binning
> turn off sending raw images in binning

- test/integration/run_gadgetron_test.py
> add /usr/local/lib into the LD_LIBRARY_PATH in run_gadgetron_test.py

- chroot/CMakeLists.txt
- chroot/gadgetron_ismrmrd_client_noise_summary.sh.in
- chroot/run-gadgetron_ismrmrd_client_noise_summary.sh.in
add scripts to call noise summary query
> add scripts for noise summary query

- gadgets/cmr/CmrCartesianKSpaceBinningCineGadget.cpp
- toolboxes/cmr/cmr_kspace_binning.cpp
- toolboxes/cmr/cmr_kspace_binning.h
- toolboxes/mri_core/mri_core_grappa.cpp
- toolboxes/mri_core/mri_core_spirit.cpp
a) Add isnan check in grappa and spirit calibration
b) Add more graceful handling for binning, mainly to handle very high heart rate case
> Fix binning failure

- toolboxes/cmr/cmr_kspace_binning.cpp
Fix a bug in binning recon
. sometimes the cardiac phase time vector can cross two heart beat
e.g.
2016-08-03 21:07:28 DEBUG [cmr_kspace_binning.cpp:1779]  n - 0 - cpt time ratio : 0.970323
2016-08-03 21:07:28 DEBUG [cmr_kspace_binning.cpp:1779]  n - 1 - cpt time ratio : 0.0933481
2016-08-03 21:07:28 DEBUG [cmr_kspace_binning.cpp:1779]  n - 2 - cpt time ratio : 0.178004
2016-08-03 21:07:28 DEBUG [cmr_kspace_binning.cpp:1779]  n - 3 - cpt time ratio : 0.262661
2016-08-03 21:07:28 DEBUG [cmr_kspace_binning.cpp:1779]  n - 4 - cpt time ratio : 0.347317
2016-08-03 21:07:28 DEBUG [cmr_kspace_binning.cpp:1779]  n - 5 - cpt time ratio : 0.431973
2016-08-03 21:07:28 DEBUG [cmr_kspace_binning.cpp:1779]  n - 6 - cpt time ratio : 0.516629
2016-08-03 21:07:28 DEBUG [cmr_kspace_binning.cpp:1779]  n - 7 …
> fix a bug in binning

- gadgets/mri_core/CMakeLists.txt
> install NHLBICompression.h

- toolboxes/core/cpu/hoNDArray_utils.h
fix a bug in the openmp of repmat call
> fix bug; ind is a shared variable; so local copies must be made

- gadgets/cmr/CMakeLists.txt
- gadgets/cmr/CmrCartesianKSpaceBinningCineGadget.cpp
- gadgets/cmr/CmrCartesianKSpaceBinningCineGadget.h
- gadgets/cmr/config/BinningCine/CMR_2DT_RTCine_KspaceBinning_Cloud.xml
- gadgets/cmr/config/BinningCine/CMR_2DT_RTCine_KspaceBinning_MultiSeries.xml
- gadgets/cmr/config/BinningCine/CMR_2DT_RTCine_KspaceBinning_MultiSeries_Cloud.xml
- gadgets/mri_core/GenericReconGadget.cpp
- gadgets/mri_core/GenericReconGadget.h
. refactor GanericReconGadget to have a function to prep image headers for sending out
. add options to let binning gadget send out multiple series
. add binning multi series xml
> add options to let binning send out multiple series

- test/CMakeLists.txt
- test/curveFitting_test.cpp
- toolboxes/operators/cpu/CMakeLists.txt
- toolboxes/operators/cpu/twoParaExpDecayOperator.h
- toolboxes/operators/curveFittingCostFunction.h
- toolboxes/operators/curveFittingOperator.h
- toolboxes/solvers/cpu/CMakeLists.txt
- toolboxes/solvers/cpu/curveFittingSolver.h
- toolboxes/solvers/cpu/simplexLagariaSolver.h
Add some solvers and operators for curve fitting
Add a unit test case to demo t2 fitting
> add some curve fitting solver and operators

- gadgets/mri_core/GenericReconCartesianGrappaGadget.cpp
- gadgets/mri_core/GenericReconCartesianReferencePrepGadget.cpp
- gadgets/mri_core/GenericReconEigenChannelGadget.cpp
- gadgets/mri_core/GenericReconFieldOfViewAdjustmentGadget.cpp
- gadgets/mri_core/GenericReconGadget.cpp
- gadgets/mri_core/GenericReconKSpaceFilteringGadget.cpp
- gadgets/mri_core/GenericReconNoiseStdMapComputingGadget.cpp
- gadgets/mri_core/GenericReconPartialFourierHandlingGadget.cpp
Open up debug output in generic chain to avoid manually change code every time to check intermediate results
> open up debug output in generic chain

- docker/base/ubuntu_1604/Dockerfile
Docker file for base image (16.04) has BART
> Added BART to base images

- toolboxes/cmr/cmr_motion_correction.cpp
- toolboxes/cmr/cmr_motion_correction.h
Add a function to apply deformation field
> add apply deformation field

- cmake/FindGadgetron.cmake
add functionalities to find gadgetron version in FindGadgetron.cmake
> add finding gadgetron version in cmake/FindGadgetron.cmake

- gadgets/bart/BART_Recon.xml
- gadgets/bart/BART_Recon_cloud.xml
- gadgets/bart/bartgadget.cpp
- gadgets/bart/bartgadget.h
We (sometimes) need a different workingDirectory from the global one, since the global one can be a network mounted drive (which is slow).
> Bart working directory

- docker/base/ubuntu_1604/Dockerfile
- gadgets/bart/BART_Recon_cloud.xml
- gadgets/bart/Sample_GRAPPA_Recon.txt
- test/integration/data.txt
New base images with stable version (0.3.01) of BART
Updated BART test cases accordingly.
> Base image updates

- docker/nvidia-docker
@xueh2 This fixes the problem with running on hosts with CUDA 8 installed.
> Nvidia docker cuda8

- gadgets/mri_core/BucketToBufferGadget.cpp
- gadgets/mri_core/BucketToBufferGadget.h
fix the ref stuffing in buffering gadget to handle the case where ref line numbers do not start from zero
> add fix for stuffing of ref separate mode

- apps/clients/gadgetron_ismrmrd_client/gadgetron_ismrmrd_client.cpp
> Error should be stderr not stdout

- gadgets/mri_noncartesian/GriddingReconGadget.cpp
add <random> include
std::mt19937 is in this header file
> add <random> for GriddingReconGadget

- toolboxes/operators/cpu/CMakeLists.txt
- toolboxes/operators/cpu/threeParaExpRecoveryOperator.h
- toolboxes/operators/cpu/twoParaExpRecoveryOperator.h
add two and three parameter exponential recovery signal operators
> add two and three para exp recovery signal operator

- gadgets/mri_core/GenericReconCartesianSpiritGadget.cpp
- toolboxes/cmr/cmr_spirit_recon.cpp
- toolboxes/core/cpu/algorithm/hoNDBSpline.hxx
- toolboxes/core/cpu/math/hoNDImage_util.hxx
- toolboxes/dwt/cpu/hoNDRedundantWavelet.cpp
- toolboxes/mri_core/mri_core_spirit.cpp
- toolboxes/registration/optical_flow/cpu/transformation/hoImageRegDeformationField.h
adjust a few openmp clauses for new visual studio  2017 compiler
all tests passed
> update for vs2017

- test/hoNDArray_utils_test.cpp
- toolboxes/core/cpu/hoNDArray_utils.h
- toolboxes/core/cpu/math/hoNDArray_elemwise.cpp
Add copy_replace function for hoNDArray_utils
Add one more instantiation for fill function
Add unit test for copy_replace
> Add ho nd array util copy replace

- toolboxes/core/cpu/hoNDArray_utils.h
- toolboxes/core/cpu/math/hoNDImage_util.hxx
- toolboxes/ffd/BSplineFFD2D.h
- toolboxes/ffd/BSplineFFD3D.h
- toolboxes/ffd/BSplineFFD4D.h
a) fix openmp for vs2017
b) update BSplineffd classes to use new fill function
> Use new fill

- test/CMakeLists.txt
- test/curveFitting_test.cpp
- toolboxes/cmr/CMakeLists.txt
- toolboxes/cmr/cmr_parametric_mapping.cpp
- toolboxes/cmr/cmr_parametric_mapping.h
- toolboxes/cmr/cmr_t1_mapping.cpp
- toolboxes/cmr/cmr_t1_mapping.h
Add cmr parametric mapping
Add T1SR mapping class
Add unit test for T1SR fitting and pixel-wise mapping
> Add cmr parametric mapping2

- toolboxes/core/cpu/math/hoNDArray_reductions.cpp
- toolboxes/core/cpu/math/hoNDArray_reductions.h
Add var functions for hoNDArray
Add more instantiation for stddev
> add var function for hoNDArray

- gadgets/dicom/dicom_ismrmrd_utility.cpp
fix bugs in the dicom conversion for the studyInformation fields
> fix dicom conversion bug

- gadgets/mri_core/GenericReconBase.h
- gadgets/mri_core/GenericReconGadget.cpp
- gadgets/mri_core/GenericReconGadget.h
fix kspace center line finding scheme for partial fourier cases
> fix the way to find kspace center

- gadgets/cmr/CmrCartesianKSpaceBinningCineGadget.h
- gadgets/cmr/CmrParametricMappingGadget.cpp
Add prep time reading from user field in the cardiac mapping.
> add prep time reading from user field

- gadgets/cmr/CmrParametricMappingGadget.cpp
- gadgets/cmr/config/Mapping/CMR_2DT_T1Mapping_SASHA.xml
first send out image, then maps
change t1 map lut names
> Adjust t1 mapping

- gadgets/mri_core/FFTGadget.cpp
As discussed at hangout 19 May. Fixes a memory leak.
> Release incoming message

- test/CMakeLists.txt
- test/pattern_recognition_test.cpp
- toolboxes/CMakeLists.txt
- toolboxes/pattern_recognition/CMakeLists.txt
- toolboxes/pattern_recognition/pr_export.h
- toolboxes/pattern_recognition/pr_kmeans.cpp
- toolboxes/pattern_recognition/pr_kmeans.h
a) Add a toolbox for pattern recognition related functions
b) As the first algorithm, add kmeans
c) this kmeans supports 4 different initialization algorithms
d) Add the unit test case for kmeans
> add toolbox pattern recognition; add kmeans

- test/CMakeLists.txt
- test/hoNDArray_reductions_test.cpp
- toolboxes/core/cpu/math/hoNDArray_reductions.cpp
- toolboxes/core/cpu/math/hoNDArray_reductions.h
Add a sort function to return sorting indexes
> add new sort functions with index

- toolboxes/pattern_recognition/pr_kmeans.cpp
fix a bug in kmeans online update
> fix a bug in pr_kmeans

- toolboxes/pattern_recognition/pr_kmeans.cpp
fix a bug in kmeans implemantion
> fix a bug in kmeans

- docker/gchroot
add option to detach all
when attach, checking whether a chroot image is already mounted; if so, return with doing nothing
> Gchroot detach all

- gadgets/mri_core/CMakeLists.txt
- gadgets/mri_core/IsmrmrdDumpGadget.cpp
- gadgets/mri_core/IsmrmrdDumpGadget.h
- gadgets/mri_core/config/Generic_ismrmrd_storage.xml
- gadgets/mri_core/config/default_measurement_dependencies_ismrmrd_storage.xml
- gadgets/mri_core/config/ismrmrd_dump.xml
- toolboxes/core/cpu/hostutils/CMakeLists.txt
- toolboxes/core/cpu/hostutils/hostutils_export.h
- toolboxes/core/cpu/hostutils/network_utils.cpp
- toolboxes/core/cpu/hostutils/network_utils.h
> Enhance ismrmrd dump

- gadgets/bart/BART_Recon.xml
- gadgets/bart/BART_Recon_cloud.xml
- gadgets/bart/CMakeLists.txt
- gadgets/bart/Sample_GRAPPA_Recon.sh
- gadgets/bart/Sample_GRAPPA_Recon.txt
- gadgets/bart/bartgadget.cpp
- gadgets/bart/bartgadget.h
Changed bart recon file from simple text file to shell script
Optimized BART source code
Added debugging option to BART
Added feature to cache BART files for better performance
Added more gadgets into BART reconstruction pipeline
> BART gadget revisited

- toolboxes/plplot/GtPLplot.cpp
- toolboxes/plplot/GtPLplot.h
- toolboxes/plplot/ut/plplot_test.cpp
Allow plotcurves to select symbols
> allow plot curves to select symbols

- chroot/CMakeLists.txt
> [CMake] cope with multiple libraries for cuda

- gadgets/python/gadgets/gadgetron.py
python complains != can be treated as element-wise comparison.
> fix the compare to None in gadgetron.py

- gadgets/bart/BART_Recon.xml
- gadgets/bart/BART_Recon_cloud.xml
- gadgets/bart/bartgadget.cpp
- gadgets/bart/bartgadget.h
Bart_Recon_cloud.xml has been fixed to make it work on distributed system / cloud.
Bart gadget has made thread safe for deployment on distributed system / cloud.
> Thread safe version of the bart gadget

- test/hoNFFT_test.cpp
- toolboxes/nfft/cpu/hoNFFT.cpp
- toolboxes/nfft/cpu/hoNFFT.h
fix compiling errors for nfft PR
> Fix ho nfft types

- test/hoNFFT_test.cpp
- test/integration/data.txt
a) Add unit test case for hoNFFT
b) Allow this test case to read in the testing data
c) The scheme is to set the env variable "GT_UNITTEST_DIRECTORY"
e) By default, GT_UNITTEST_DIRECTORY should be $GADGETRON_SOURCE_DIR/test/integration/data/ut
f) data.txt is updated, so these data can be downloaded
> add test data for nfft test_all

- gadgets/bart/bartgadget.cpp
Fixed memory leak
Minor housekeeping for better performance
> Fixed memory leak

- docker/start_supervisor
- toolboxes/registration/optical_flow/cpu/application/hoImageRegContainer2DRegistration.h
avoid the nested openmp to spin out too many threads
> make nested openmp use less threads

- apps/matlab/CMakeLists.txt
- apps/matlab/Matlab_gt_apply_deformation_field_reg_2D_series.cpp
- apps/matlab/Matlab_gt_deformation_field_reg_2D.cpp
- apps/matlab/Matlab_gt_deformation_field_reg_2D_series.cpp
- apps/matlab/Matlab_gt_deformation_field_reg_2D_series_pairwise.cpp
- toolboxes/core/cpu/hoMatrix.hxx
add some mex for moco applications
> add mex for moco

- docker/base/ubuntu_1604_cuda80_cudnn7/Dockerfile
- docker/build_base_images.sh
- docker/incremental/ubuntu_1604_cuda80_cudnn7/Dockerfile
Add docker file to build cuda8 image with cudnn7
Install tensorflow
Extend the build base image script
> Add cuda80 cudnn docker

- gadgets/mri_core/BucketToBufferGadget.cpp
fix the empty bucket detection by counting ref data size as well
@ojosephs Please review.
> fix the detection of empty bucket

- gadgets/cmr/CmrCartesianKSpaceBinningCineGadget.cpp
- gadgets/cmr/CmrCartesianKSpaceBinningCineGadget.h
allow binning to decide whether to send out multi-series for multi-slices
it is a common usecase
> allow binning to send out every slice as a series

- toolboxes/core/cpu/math/hoNDArray_reductions.cpp
- toolboxes/core/cpu/math/hoNDArray_reductions.h
> add linFit function in hoNDArray_reductions

- gadgets/cmr/CMakeLists.txt
- gadgets/cmr/CmrParametricMappingGadget.cpp
- gadgets/cmr/CmrParametricMappingGadget.h
- gadgets/cmr/CmrParametricT1SRMappingGadget.cpp
- gadgets/cmr/CmrParametricT2MappingGadget.cpp
- gadgets/cmr/CmrParametricT2MappingGadget.h
- test/CMakeLists.txt
- test/cmr_mapping_test.cpp
- test/hoNDArray_reductions_test.cpp
- toolboxes/cmr/CMakeLists.txt
- toolboxes/cmr/cmr_t2_mapping.cpp
- toolboxes/cmr/cmr_t2_mapping.h
add t2 mapping gadget and cmr toolbox classes.
> add t2 mapping

- toolboxes/cmr/cmr_parametric_mapping.cpp
- toolboxes/cmr/cmr_parametric_mapping.h
- toolboxes/cmr/cmr_t1_mapping.cpp
- toolboxes/cmr/cmr_t1_mapping.h
- toolboxes/cmr/cmr_t2_mapping.cpp
- toolboxes/cmr/cmr_t2_mapping.h
add more checks for t1/t2 mapping max/min values
> Improve mapping max min

- gadgets/mri_core/CMakeLists.txt
- toolboxes/cmr/cmr_time_stamp.cpp
- toolboxes/cmr/cmr_time_stamp.h
Add utility function for cmr phase resampling
> Add cmr phase interp

- gadgets/dicom/dicom_ismrmrd_utility.cpp
This modifies the dicom gadget to work with most ismrmrd datasets, even when system information is missing.
> Modified dicom_ismrmrd_utility to be more forgiving

- gadgets/plplot/Generic_Cartesian_Grappa_SNR_CoilQA.xml
For CoilQA xml, add the coil compression to faster recon.
> add coil compression for CoilQA xml

- cmake/FindPLplot.cmake
Fix FindPLplot script, mainly for ubuntu 18.04
> extend FindPLplot script for Ubuntu 18.04

- gadgets/mri_core/BucketToBufferGadget.cpp
- gadgets/mri_core/GenericReconGadget.cpp
- test/python_converter_test.cpp
- toolboxes/python/python_IsmrmrdImageArray_converter.h
- toolboxes/python/python_IsmrmrdReconData_converter.h
- toolboxes/python/python_ismrmrd_converter.h
- toolboxes/python/python_toolbox.cpp
- toolboxes/python/python_toolbox.h
Updates Gadgetron to compile with latest Ismrmrd
> Ismrmrd update

- gadgets/mri_core/NoiseAdjustGadget.cpp
- gadgets/mri_core/NoiseAdjustGadget.h
extend noise adjust gadget to handle the case where order of channels is different between noise and imaging data.
> extend NoiseAdjustGadget to check ordre of channels

- gadgets/mri_core/NoiseAdjustGadget.cpp
if order of coils should be switched, adjust the noise co-variance matrix.
> further fix coil order adjust

- gadgets/distributed/DistributeGadget.cpp
- gadgets/distributed/DistributeGadget.h
extend DistributeGadget to allow testing whether node is alive
> Add check distribute gadget

- gadgets/bart/Sample_Grappa_Recon.sh
- gadgets/bart/Sample_Grappa_Recon_Standard.sh
Remove "rsense" which is no longer supported by new version of BART
Provide some new reconstruction parameters for better image quality
> Modified reconstruction scripts

- gadgets/mri_core/GenericReconCartesianFFTGadget.cpp
- gadgets/mri_core/GenericReconCartesianGrappaGadget.cpp
- gadgets/mri_core/GenericReconCartesianGrappaGadget.h
- gadgets/mri_core/GenericReconCartesianReferencePrepGadget.cpp
- gadgets/mri_core/GenericReconCartesianSpiritGadget.cpp
- toolboxes/mri_core/mri_core_data.h
fix some memory leakage in generic chains
> fix some memory leakage

- gadgets/mri_core/CMakeLists.txt
- toolboxes/registration/optical_flow/cpu/CMakeLists.txt
- toolboxes/registration/optical_flow/cpu/application/hoImageRegContainer2DRegistration.h
- toolboxes/registration/optical_flow/cpu/dissimilarity/hoImageRegDissimilarity.h
- toolboxes/registration/optical_flow/cpu/dissimilarity/hoImageRegDissimilarityHistogramBased.h
- toolboxes/registration/optical_flow/cpu/dissimilarity/hoImageRegDissimilarityLocalCCR.h
- toolboxes/registration/optical_flow/cpu/dissimilarity/hoImageRegDissimilarityMutualInformation.h
- toolboxes/registration/optical_flow/cpu/dissimilarity/hoImageRegDissimilarityNormalizedMutualInformation.h
- toolboxes/registration/optical_flow/cpu/dissimilarity/hoImageRegDissimilaritySSD.h
- toolboxes/registration/optical_flow/cpu/register/hoImageRegDeformationFieldBidirectionalRegister.h
- toolboxes/registration/optical_flow/cpu/register/hoImageRegDeformationFieldRegister.h
- toolboxes/registration/optical_flow/cpu/register/hoImageRegNonParametricRegister.h
- toolboxes/registration/optical_flow/cpu/register/hoImageRegParametricRegister.h
- toolboxes/registration/optical_flow/cpu/register/hoImageRegRegister.h
- toolboxes/registration/optical_flow/cpu/solver/hoImageRegDeformationFieldBidirectionalSolver.h
- toolboxes/registration/optical_flow/cpu/solver/hoImageRegDeformationFieldSolver.h
- toolboxes/registration/optical_flow/cpu/solver/hoImageRegNonParametricSolver.h
- toolboxes/registration/optical_flow/cpu/solver/hoImageRegParametricDownHillSolver.h
- toolboxes/registration/optical_flow/cpu/solver/hoImageRegParametricGradientDescentSolver.h
- toolboxes/registration/optical_flow/cpu/solver/hoImageRegParametricSolver.h
- toolboxes/registration/optical_flow/cpu/solver/hoImageRegSolver.h
- toolboxes/registration/optical_flow/cpu/transformation/hoImageRegDeformationField.h
- toolboxes/registration/optical_flow/cpu/transformation/hoImageRegHomogenousTransformation.h
- toolboxes/registration/optical_flow/cpu/transformation/hoImageRegNonParametricTransformation.h
- toolboxes/registration/optical_flow/cpu/transformation/hoImageRegParametricTransformation.h
- toolboxes/registration/optical_flow/cpu/transformation/hoImageRegRigid2DTransformation.h
- toolboxes/registration/optical_flow/cpu/transformation/hoImageRegRigid3DTransformation.h
- toolboxes/registration/optical_flow/cpu/transformation/hoImageRegTransformation.h
- toolboxes/registration/optical_flow/cpu/warper/hoImageRegWarper.h
add more changes to moco package
> add more features to moco

- gadgets/mri_core/CMakeLists.txt
- gadgets/mri_core/GenericImageReconGadget.cpp
- gadgets/mri_core/GenericImageReconGadget.h
- gadgets/mri_core/GenericReconAccumulateImageTriggerGadget.cpp
- gadgets/mri_core/GenericReconAccumulateImageTriggerGadget.h
- test/integration/cases/generic_grappa_snr_R3_tpat__PEFOV100_PERes120.cfg
- toolboxes/mri_core/mri_core_data.h
- toolboxes/mri_core/mri_core_def.h
- toolboxes/mri_core/mri_core_utility.cpp
- toolboxes/mri_core/mri_core_utility.h
Add image recon base gadgets in generic chain
Add more utility functions
> add image recon gadgets

- test/integration/run_gadgetron_test.py
add time out for stopping gadgetron in python integration test
> add timeout for stopping gadgetron

- gadgets/mri_core/CMakeLists.txt
- gadgets/mri_core/GenericImageReconArrayToImageGadget.cpp
- gadgets/mri_core/GenericImageReconArrayToImageGadget.h
- gadgets/mri_core/GenericImageReconGadget.cpp
- gadgets/mri_core/GenericImageReconGadget.h
- toolboxes/core/cpu/hoNDArray.h
- toolboxes/core/cpu/hoNDObjectArray.h
Allow image recon gadget to send out image array
> Add more image recon gadgets

- gadgets/fatwater/config/Generic_Cartesian_Grappa_FatWater.xml
- toolboxes/fatwater/FatWaterFitting.cpp
- toolboxes/fatwater/correct_frequency_shift.cpp
Changed the gradient descent based fat-water optimization to be more robust.
> Fixed the frequency shift correction. 

- apps/gadgetron/CMakeLists.txt
- apps/gadgetron/EndGadget.h
- apps/gadgetron/GadgetStreamInterface.h
- gadgets/mri_core/DenoiseGadget.cpp
- gadgets/mri_core/DenoiseGadget.h
- toolboxes/denoise/non_local_bayes.cpp
> fix the windows compilation

- gadgets/mri_core/BucketToBufferGadget.cpp
- gadgets/mri_core/GenericReconCartesianFFTGadget.cpp
- gadgets/mri_core/GenericReconCartesianGrappaGadget.cpp
- gadgets/mri_core/GenericReconCartesianSpiritGadget.cpp
- gadgets/python/PythonGadget.cpp
- gadgets/python/PythonGadget.h
- gadgets/python/gadgets/bucket_recon.py
- gadgets/python/gadgets/gadgetron.py
- test/python_converter_test.cpp
- toolboxes/mri_core/mri_core_data.h
- toolboxes/python/example/demo.cpp
- toolboxes/python/python_IsmrmrdReconData_converter.h
make waveform separate message for recon data
> Refactor waveform

- gadgets/mri_core/GenericImageReconArrayToImageGadget.cpp
- gadgets/mri_core/GenericImageReconGadget.cpp
- gadgets/mri_core/GenericImageReconGadget.h
- gadgets/mri_core/GenericReconAccumulateImageTriggerGadget.cpp
- gadgets/mri_core/GenericReconAccumulateImageTriggerGadget.h
- toolboxes/core/cpu/hoNDObjectArray.h
Fix memory leakage in the image processing gadgets
Pass the sanitize compilation tests
> Fix mem leak

- docker/base/ubuntu_1604_cuda80_cudnn6/Dockerfile
- docker/base/ubuntu_1604_cuda80_cudnn7/Dockerfile
- docker/base/ubuntu_1604_cuda90_cudnn7/Dockerfile
- docker/base/ubuntu_1804/Dockerfile
- docker/base/ubuntu_1804_cuda90/Dockerfile
- docker/base/ubuntu_1804_cuda92_cudnn7/Dockerfile
- docker/incremental/ubuntu_1604_cuda80_cudnn6/Dockerfile
- docker/incremental/ubuntu_1604_cuda80_cudnn7/Dockerfile
- docker/incremental/ubuntu_1604_cuda90_cudnn7/Dockerfile
- docker/incremental/ubuntu_1604_no_cuda/Dockerfile
- docker/incremental/ubuntu_1804_cuda90_cudnn7/Dockerfile
- docker/incremental/ubuntu_1804_cuda92_cudnn7/Dockerfile
- docker/incremental/ubuntu_1804_no_cuda/Dockerfile
This commit replaces `make -j 16` with `make -j $(nproc)` in Dockerfiles. Closes #655
> Fixed -j 16 to nproc to adjust to available system resources

- toolboxes/denoise/non_local_bayes.cpp
refactor the denoising code
a) separate critical part of code out
b) make the parallel part of code run without barrier
it can now run ~700ms on my desktop, original it was running at ~2s
> improve the scalability of non local denoising

- toolboxes/denoise/non_local_bayes.cpp
Reverts gadgetron/gadgetron#661
> Revert "improve the scalability of non local denoising"

- cmake/CMakeLists.txt
- toolboxes/python/CMakeLists.txt
- toolboxes/python/example/CMakeLists.txt
- toolboxes/python/example/demo.cpp
- toolboxes/python/python_toolbox.h
add PythonFunction to return bp::object
add installation for missing cmake files
> Test python call in cplusplus

- docker/base/ubuntu_1604_cuda92_cudnn7/Dockerfile
add ubuntu 16.04 cuda 92 docker file
> add docker/base/ubuntu_1604_cuda92_cudnn7/Dockerfile

- docker/base/ubuntu_1604/Dockerfile
since boost process is only available in and after 1.64.0, we have to compile boost in ubuntu 16.04.
> Ubuntu1604 update boost

- gadgets/matlab/MatlabGadget.cpp
- toolboxes/matlab/MatlabUtils.cpp
Unfortunately, I don't have the time to fully test those changes right now.
> Add support for the new MATLAB complex interleaved API

- CMakeLists.txt
Explicit check for boost version. Closes #671
> Checking boost version

- gadgets/cmr/config/BinningCine/CMR_2DT_RTCine_KspaceBinning.xml
- gadgets/cmr/config/BinningCine/CMR_2DT_RTCine_KspaceBinning_Cloud.xml
- gadgets/cmr/config/BinningCine/CMR_2DT_RTCine_KspaceBinning_MultiSeries.xml
- gadgets/cmr/config/BinningCine/CMR_2DT_RTCine_KspaceBinning_MultiSeries_Cloud.xml
- gadgets/cmr/config/Mapping/CMR_2DT_T1Mapping_SASHA.xml
- gadgets/mri_core/config/Generic_Cartesian_FFT.xml
- gadgets/mri_core/config/Generic_Cartesian_Grappa.xml
- gadgets/mri_core/config/Generic_Cartesian_Grappa_EPI.xml
- gadgets/mri_core/config/Generic_Cartesian_Grappa_EPI_AVE.xml
- gadgets/mri_core/config/Generic_Cartesian_Grappa_RealTimeCine.xml
- gadgets/mri_core/config/Generic_Cartesian_Grappa_RealTimeCine_Cloud.xml
- gadgets/mri_core/config/Generic_Cartesian_Grappa_SNR.xml
- gadgets/mri_core/config/Generic_Cartesian_Grappa_T2W.xml
- gadgets/mri_core/config/Generic_Cartesian_NonLinear_Spirit_RealTimeCine.xml
- gadgets/mri_core/config/Generic_Cartesian_NonLinear_Spirit_RealTimeCine_Cloud.xml
- gadgets/mri_core/config/Generic_Cartesian_RandomSampling_NonLinear_Spirit_RealTimeCine.xml
- gadgets/mri_core/config/Generic_Cartesian_RandomSampling_NonLinear_Spirit_RealTimeCine_Cloud.xml
- gadgets/mri_core/config/Generic_Cartesian_Spirit.xml
- gadgets/mri_core/config/Generic_Cartesian_Spirit_RealTimeCine.xml
- gadgets/mri_core/config/Generic_Cartesian_Spirit_SASHA.xml
- gadgets/plplot/Generic_Cartesian_Grappa_SNR_CoilQA.xml
- gadgets/python/CMakeLists.txt
- gadgets/python/config/Generic_Cartesian_Grappa_RealTimeCine_Python.xml
- gadgets/python/config/python_passthrough.xml
- gadgets/python/gadgets/image_array_recon.py
- gadgets/python/gadgets/image_array_recon_rtcine_plotting.py
. Fix the group names in some xmls
. Add a python example for multi-slice rt cine processing
> Save image array data python

- test/integration/get_data.py
The download progress updates from the get_data.py script left a lot of noise in our logs. I've introduced a flag to disable them (--mute-download-progress).
> Adding flag for muting download progress.

- test/integration/run_gadgetron_test.py
Adding some exception handling to deal specifically with missing test data.
> Improving test script message when no output is produced.

- CMakeLists.txt
- cmake/CMakeLists.txt
- cmake/FindBART.cmake
- gadgets/CMakeLists.txt
> Add FindBART.cmake file

- cmake/FindPython3.cmake
Added Python 3.7 support to FindPython3.cmake
> Updated FindPython3.cmake to support Python 3.7

- toolboxes/core/cpu/image/hoNDImageContainer2D.h
Add more create functions in hoNDImageContainer2D
. to allow every row of images has different image size
> add more create functions for hoNDImageContainer2D

- docker/base/ubuntu_1604/Dockerfile
- docker/base/ubuntu_1604_basic/Dockerfile
- docker/base/ubuntu_1604_cuda100_cudnn7/Dockerfile
- docker/base/ubuntu_1604_cuda92_cudnn7/Dockerfile
- docker/base/ubuntu_1804/Dockerfile
- docker/base/ubuntu_1804_cuda100_cudnn7/Dockerfile
- docker/base/ubuntu_1804_cuda90/Dockerfile
- docker/base/ubuntu_1804_cuda92_cudnn7/Dockerfile
use pytorch 1.0
Update Dockerfile
Update Dockerfile
Update Dockerfile
Update Dockerfile
Update Dockerfile
Update Dockerfile
Update Dockerfile
Update Dockerfile
install numpy 1.15.4
Update Dockerfile
Update Dockerfile
Update Dockerfile
Update Dockerfile
Update Dockerfile
Update Dockerfile
Update Dockerfile
> update docker to use pytorch 1.0

- toolboxes/nfft/cpu/CMakeLists.txt
> added the header of hoNFFT_sparseMatrix.h to the cmake file

- toolboxes/nfft/NFFT.h
> Remove virtual from methods

- gadgets/mri_core/GenericReconCartesianGrappaGadget.cpp
- toolboxes/CMakeLists.txt
- toolboxes/mri_core/CMakeLists.txt
- toolboxes/mri_core/mri_core_grappa.cpp
- toolboxes/mri_core/mri_core_grappa.h
- toolboxes/mri_core/mri_core_grappa_python.cpp
- toolboxes/mri_core/mri_core_grappa_python.h
- toolboxes/mri_core/mri_core_python.cpp
a. add grappa kspace recon for 2d
b. refactor grappa 2d calibration for prepare and perform, two parts
c. add mri_core_python for python binding
d. add python binding grappa2D for grappa function; works in python now
> add mri core python binding; first for grappa

- docker/base/ubuntu_1604_cuda101_cudnn7/Dockerfile
- docker/base/ubuntu_1804_cuda101_cudnn7/Dockerfile
- docker/build_base_images.sh
- docker/push_base_images.sh
add docker base image file for cuda 10.1
> Add cuda101

- gadgets/mri_core/GenericReconGadget.cpp
- gadgets/mri_core/GenericReconGadget.h
add more controls for coil map estimation
> add more controls for coil map estimation parameters

- gadgets/mri_core/GenericReconCartesianGrappaGadget.cpp
fix grappa recon for no downstream coil compression
> fix grappa recon without down stream coil compression

- gadgets/CMakeLists.txt
- gadgets/mri_core/CMakeLists.txt
- gadgets/mri_core/GenericReconCartesianGrappaAIGadget.cpp
- gadgets/mri_core/GenericReconCartesianGrappaAIGadget.h
- gadgets/mri_core/config/Generic_Cartesian_Grappa_AI.xml
- gadgets/python/CMakeLists.txt
- gadgets/python/models/grappa_ai.py
Add a gadget to do grappa.ai (run grappa as a NN).
This servers an example for how to call NN inside gadgetron for mr recon.
> add grappa ai gadget and xml

- gadgets/epi/EPICorrGadget.cpp
make sure some variables are always initializied
> fix a variable initialization problem in EPICorrGadget.cpp

- docker/base/ubuntu_1604/Dockerfile
- docker/base/ubuntu_1604_basic/Dockerfile
- docker/base/ubuntu_1604_cuda100_cudnn7/Dockerfile
- docker/base/ubuntu_1804/Dockerfile
- docker/base/ubuntu_1804_cuda100_cudnn7/Dockerfile
update docker file to use pytorch 1.1 and torchvision 0.3
> update base image docker to use pytorch 1p1

- apps/matlab/CMakeLists.txt
- apps/standalone/cpu/gtplus/CMakeLists.txt
- gadgets/CMakeLists.txt
> Fix matlab apps

- cmake/CMakeLists.txt
- test/CMakeLists.txt
- test/cmr_strain_test.cpp
- toolboxes/cmr/cmr_strain_analysis.cpp
- toolboxes/mri_core/mri_core_def.h
fix strain analysis
add data role for strain mapping
> add strain data role; fix cmr_strain_analysis

- test/cmr_strain_test.cpp
- toolboxes/cmr/cmr_strain_analysis.cpp
add openmp to strain mapping
further reformat the code
> further refine cmr strain analysis and test

- apps/matlab/CMakeLists.txt
- apps/matlab/Matlab_gt_apply_deformation_field_reg_2D_series.cpp
- apps/matlab/Matlab_gt_concatenate_deform_fields.cpp
- apps/matlab/Matlab_gt_deformation_field_reg_2D.cpp
- apps/matlab/Matlab_gt_deformation_field_reg_2D_series.cpp
- apps/matlab/Matlab_gt_deformation_field_reg_2D_series_pairwise.cpp
- gadgets/matlab/MatlabBucketReconGadget.cpp
- gadgets/mri_core/CMakeLists.txt
- gadgets/mri_core/GenericReconAccumulateImageTriggerGadget.cpp
- gadgets/mri_core/ImageResizingGadget.cpp
- gadgets/mri_core/ImageResizingGadget.h
- test/cmr_strain_test.cpp
- toolboxes/cmr/CMakeLists.txt
- toolboxes/cmr/cmr_kspace_binning.cpp
- toolboxes/cmr/cmr_kspace_binning.h
- toolboxes/cmr/cmr_motion_correction.cpp
- toolboxes/cmr/cmr_motion_correction.h
- toolboxes/cmr/cmr_parametric_mapping.cpp
- toolboxes/cmr/cmr_strain_analysis.cpp
- toolboxes/cmr/cmr_strain_analysis.h
- toolboxes/core/cpu/algorithm/hoNDBSpline.h
- toolboxes/core/cpu/image/hoNDImage.h
- toolboxes/operators/cpu/hoMotionCompensation2DTOperator.cpp
- toolboxes/operators/cpu/hoWavelet2DTOperator.h
- toolboxes/registration/optical_flow/cpu/register/hoImageRegDeformationFieldRegister.h
- toolboxes/registration/optical_flow/cpu/solver/hoImageRegDeformationFieldSolver.h
- toolboxes/registration/optical_flow/cpu/transformation/hoImageRegDeformationField.h
- toolboxes/registration/optical_flow/cpu/warper/hoImageRegWarper.h
Modify the moco toolbox to use double deformation field to improve accuracy
Modify API to call moco
> Update nd image coord use double

- gadgets/cmr/CmrCartesianKSpaceBinningCineGadget.cpp
- toolboxes/cmr/cmr_kspace_binning.cpp
- toolboxes/cmr/cmr_kspace_binning.h
Extend binning saving, so different slices are saved in different arrays
> Extend binning for multi slices

- test/integration/run_tests.py
Add controls to run all cases even failure
> Run tests script

- test/integration/run_gadgetron_test.py
- test/integration/run_tests.py
Reverts gadgetron/gadgetron#768
> Revert "import run_tests from GT 4.0"

- CMakeLists.txt
- cmake/gadgetron_sha1.h.in
- gadgets/mri_core/GenericReconBase.h
- gadgets/mri_core/GenericReconGadget.cpp
- toolboxes/cmr/cmr_radial_thickening.cpp
allow gadgetron to have its sha1 when compiled
add sha1 to every reconed image to indicate its version
> add gadgetron sha1 header

- gadgets/mri_core/MaxwellCorrectionGadget.cpp
- gadgets/mri_core/MaxwellCorrectionGadget.h
Many thanks for @MRIOSU, Chong Chen. He did lots of work to fix the maxwell correction gadget. It will improve the flow imaging in Gadgetron.
> fix maxwell correction

- test/integration/data.json
- test/integration/run_tests.py
Added missing test data to list; added data- and test folder arguments to 'run_tests' script.
> Fixed missing test data in data list.

- toolboxes/core/cpu/ho2DArray.h
- toolboxes/core/cpu/ho3DArray.h
- toolboxes/core/cpu/ho4DArray.h
- toolboxes/core/cpu/ho5DArray.h
- toolboxes/core/cpu/ho6DArray.h
- toolboxes/core/cpu/ho7DArray.h
- toolboxes/core/cpu/hoMatrix.h
Exchanged angular brackets with quotation marks for template includes in core/cpu
> Fixes #793

- apps/gadgetron/connection/Config.cpp
- apps/gadgetron/connection/Config.h
- core/CMakeLists.txt
- core/Channel.cpp
- core/Channel.h
- core/Channel.hpp
- core/ChannelIterator.h
- core/parallel/CMakeLists.txt
- core/parallel/UnorderedMerge.cpp
- core/parallel/UnorderedMerge.h
UnorderedMerge is a default merge node that just passes on input from any parallel stream in the order it arrives. Also cleaned up a few things in the Config code.
> Introducing UnorderedMerge

- core/writers/AcquisitionWriter.cpp
- core/writers/AcquisitionWriter.h
- core/writers/CMakeLists.txt
- core/writers/WaveformWriter.cpp
- core/writers/WaveformWriter.h
- gadgets/mri_core/writers/GadgetIsmrmrdWriter.cpp
- gadgets/mri_core/writers/GadgetIsmrmrdWriter.h
Introduced an AcquisitionWriter and a WaveformWriter in Gadgetron::Core::Writers. Legacy writers are aliases.
> Introduced an AcquisitionWriter and a WaveformWriter.

- apps/gadgetron/Server.cpp
- apps/gadgetron/paths.cpp
Fix a debug message at start.
Add additional info messages at start.
> Aymeric chataigner/fix directory path info

- docker/base/ubuntu_2004_basic/Dockerfile
- docker/incremental/ubuntu_2004/Dockerfile
add docker file for ubuntu 2004
> add docker file for ubuntu 2004

- gadgets/T1/T1MocoGadget.cpp
- gadgets/T1/config/MOLLI_T1_Moco.xml
A few changes:
a) Change image sending order to origin,moco,T1
b) Add TI times to moco series
c) Make sure image sent as short
> Fix t1 mapping 3

- gadgets/T1/CMakeLists.txt
- gadgets/T1/config/MOLLI_T1_Moco_istore.xml
> add MOLLI_T1_Moco_istore.xml

- toolboxes/mri/pmri/gpu/b1_map.cu
This adds a new overload for function `smooth_correlation_matrices_border_kernel`, so that `estimate_b1_map` can be called on 3D images.
> Add support for 3D CSM estimation using GPU

- apps/gadgetron/CMakeLists.txt
- core/readers/AcquisitionReader.cpp
- core/writers/AcquisitionWriter.cpp
- core/writers/AcquisitionWriter.h
Fixed issue where acquisition trajectories were never written to external languages.
> Trajectory Fix

- gadgets/cmr/CMakeLists.txt
- gadgets/cmr/config/LandmarkDetection/CMR_Image_Chain_RTCine_LAX_AI.xml
- gadgets/mri_core/CMakeLists.txt
- gadgets/mri_core/GenericReconImageToImageArrayGadget.cpp
- gadgets/mri_core/GenericReconImageToImageArrayGadget.h
- gadgets/mri_core/ImageFFTGadget.cpp
- gadgets/mri_core/ImageFFTGadget.h
- gadgets/mri_core/config/Generic_Cartesian_Image_Chain_FFT.xml
Add a pure image processing chain for demo to do FFT on incoming images
> add an example image chain

- apps/clients/gadgetron_ismrmrd_client/gadgetron_ismrmrd_client.cpp
This adds data transmission statistics to the gadgetron_ismrmrd_client when the `-v` option is enabled. This is useful for testing connection speeds. It complements tools like `iperf` and `iperf3` by providing a measurement specific to a reconstruction scenario.
> Added some gadgetron ismrmrd client transmission rate metrics

- toolboxes/nfft/gpu/ConvolverNC2C_atomic.cu
Due to atomicAdd not being defined for GPUs with compute capability less than 6.0, Gadgetron currently fails to compile on these platforms with the following error:
```
/opt/code/gadgetron/toolboxes/nfft/gpu/ConvolverNC2C_atomic.cu(55): error: no instance of overloaded function "atomicAdd" matches the argument list
```
This PR fixes the problem.
> Fix for older GPU compute capability.

- docker/incremental/ubuntu_2004/Dockerfile
add missing installation in pip3
> add missing ismrmrd pip installation

- apps/gadgetron/CMakeLists.txt
only need this linking to make all targets built
> fix gadgetron linkage in windows

- azure-pipelines.yml
- docker/install_ubuntu_dependencies.sh
- docker/ubuntu_base.Dockerfile
This PR adds builds for 18.04 images.
> 18.04 image builds

- test/integration/cases/generic_grappa2x1_3d.cfg
- test/integration/cases/generic_grappa2x2_3d.cfg
- test/integration/data.json
As discussed with @hansenms in https://github.com/gadgetron/gadgetron/issues/854, I have added the integration test for 3D grappa datasets.
You need to add these [files](https://www.rmsb.u-bordeaux.fr/rmsbcloud/s/e8nokgnsCBZWgME) to http://gadgetrondata.blob.core.windows.net/gadgetrontestdata/
> Add grappa_3D unit test

- docker/install_ubuntu_dependencies.sh
- test/integration/data.json
- test/integration/get_data.py
Also fixed get_data.py to work with unstable blob storage providers ;)
> Added missing ismrmrd-python and gadgetron-python

- gadgets/T1/T1MocoGadget.cpp
- toolboxes/T1/t1fit.cpp
Changed default window level setting for T1 error map. Changed implementation to use the unbiased median absolute deviation
> Updated T1 error map

- gadgets/mri_core/AcquisitionAccumulateTriggerGadget.h
- toolboxes/mri_core/mri_core_def.h
- toolboxes/plplot/GtPLplot.cpp
- toolboxes/plplot/GtPLplot.h
reformat a line of code
fix typo
update plplot lib
> update plplot lib; fix typos; reformat a line of code

- gadgets/cmr/CmrRealTimeLAXCineAIAnalysisGadget.cpp
- gadgets/mri_core/GenericImageReconGadget.cpp
GenericImageReconGadget.cpp, add check for whether image has pixels
make sure image size be even in gadgets/cmr/CmrRealTimeLAXCineAIAnaly…
> two fixes for gadgets

- toolboxes/cmr/cmr_image_container_util.cpp
fix openmp in toolboxes/cmr/cmr_image_container_util.cpp
> fix openmp in toolboxes/cmr/cmr_image_container_util.cpp

- apps/standalone/gpu/denoising/2d/CMakeLists.txt
- toolboxes/core/gpu/CMakeLists.txt
- toolboxes/dwt/gpu/CMakeLists.txt
> Fixing some Python linking issues for standalone apps.

- apps/clients/gadgetron_ismrmrd_client/gadgetron_ismrmrd_client.cpp
- cmake/FindZFP.cmake
- docker/install_ubuntu_dependencies.sh
- gadgets/mri_core/readers/GadgetIsmrmrdReader.cpp
The ZFP compression library was disabled. This re-enables it.
> Re-enabled ZFP compression library

- test/integration/run_tests.py
Fixed issue where test script would not work as expected when using `--ignore-requirements=all`.
> Fix for --ignore-requirements=all issue.

- test/integration/run_gadgetron_test.py
This pull request is a fix for #1032 (we think)
@kristofferknudsen discovered that this was a result of the storage server not being ready. The test script now waits for both the storage server and gadgetron itself to be ready and receiving connections before continuing.
> Updated test script to wait for storage and gadgetron server to be ready

- README.md
- environment.yml
Small PR to adjust the readme text to use latest conda packages (to provide clear navigation around the [CUDA 11.6.0 conda issue](https://forums.developer.nvidia.com/t/conda-packages-from-the-nvidia-label-cuda-11-6-0-failing-to-install/204281). Also pulls in minor patches on a couple of dependencies.
> Touch up of README and update ISMRMRD to 1.7.1 and converter to 1.2.2

- environment.yml
> Pulling in new ismrmrd-python version

- doc/source/index.rst
- doc/source/using.md
This PR moves the previous "hello world" example from the wiki. Once merged, we will delete it from the wiki.
> Move the hello world example to the docs

- core/gadgetron_paths.cpp
Should not affect Linux builds as these changes are in "__APPLE__" section of code.
> Adding missing header file and function definition in an "__APPLE__" section of code.

- gadgets/mri_core/CombineGadget.cpp
- gadgets/mri_core/CombineGadget.h
Continuing #1087 , this PR converts CombineGadget to a PureGadget using the conventions established in #1090  and #1094
> CombineGadget->PureGadget Conversion

- gadgets/mri_core/CoilReductionGadget.cpp
- gadgets/mri_core/CoilReductionGadget.h
Continuing #1087 , this PR converts CoilReductionGadget to a ChannelGadget using the conventions established in #1090 and #1094
> CoilReductionGadget->ChannelGadget Conversion

- azure-pipelines.yml
- environment.yml
Minor clean-up of environment file to use (newer) junitparser conda package.
Also slightly re-work Azure build configuration, so jobs can be assigned to various hardware platforms in build pipeline.
> Update environment to use junitparser from condo-forge, and stage azure build configuration for macOS

- CMakeLists.txt
- gadgets/mri_core/generic_recon_gadgets/GenericImageReconGadget.h
- gadgets/mri_core/generic_recon_gadgets/GenericReconCartesianGrappaGadget.h
- test/cuNDArray_blas_test.cpp
- toolboxes/core/cpu/hoNDArray_utils.h
- toolboxes/core/cpu/hoNDInterpolator.h
- toolboxes/ffd/BSplineFFD.h
This PR should address some virtual/override function issues when compiling with Clang, as well as function deprecations in GTest picked up by Clang.
> More patches to allow compilation with Clang

- gadgets/dicom/dicom_ismrmrd_utility.cpp
> Remove build warning

- .readthedocs.yaml
- doc/source/requirements.txt
Added readthedocs config file.
https://docs.readthedocs.io/en/stable/config-file/v2.html
> added readthedocs config

- toolboxes/core/gpu/cuNDArray_utils.cu
- toolboxes/core/vector_td.h
- toolboxes/operators/gpu/cuPartialDerivativeOperator.cu
- toolboxes/operators/gpu/cuPartialDerivativeOperator2.cu
Minor update needed to support 5D recons.
> added 5d vector support

- core/Response.h
- core/gadgetron_paths.cpp
- gadgets/mri_core/readers/GadgetIsmrmrdReader.cpp
- gadgets/mri_noncartesian/GriddingReconGadgetBase.hpp
- test/integration/run_gadgetron_test.py
- toolboxes/image_io/ImageIOAnalyze.h
- toolboxes/solvers/cpu/HybridLM.h
merge in the fix for deployment
> further fix missing headers; update ARMA macros

- gadgets/mri_core/AcquisitionAccumulateTriggerGadget.cpp
- gadgets/mri_core/generic_recon_gadgets/GenericReconAccumulateImageTriggerGadget.cpp
- gadgets/mri_core/generic_recon_gadgets/GenericReconAccumulateImageTriggerGadget.h
- gadgets/mri_core/generic_recon_gadgets/GenericReconCartesianGrappaAIGadget.cpp
- gadgets/mri_core/generic_recon_gadgets/GenericReconCartesianGrappaGadget.cpp
- gadgets/mri_core/generic_recon_gadgets/GenericReconCartesianSpiritGadget.cpp
- gadgets/mri_core/generic_recon_gadgets/GenericReconGadget.cpp
- gadgets/mri_core/generic_recon_gadgets/GenericReconGadget.h
fix the wave form accumulation and passing
> bring in waveform fix

- azure-pipelines.yml
- build-images.sh
- conda/meta.yaml
- environment.yml
- gadgets/mri_core/BucketToBufferGadget.cpp
- gadgets/mri_core/BucketToBufferGadget.h
- gadgets/mri_core/generic_recon_gadgets/GenericReconCartesianGrappaGadget.cpp
- test/integration/cases/ismrmrd_dump_gadget_test.cfg
- test/integration/data.json
- test/mri_core_stream_test.cpp
- toolboxes/mri_core/mri_core_def.h
- toolboxes/mri_core/mri_core_stream.cpp
- toolboxes/mri_core/mri_core_stream.h
- stream out waveform
- stream out kspace hondarry as ismrmrd nd array
- add more tests for all these use cases
> Add waveform stream and use ismrmrd ndarray
